### ISSUE TITLE
Setup de ambiente dev no computador da Vanessa

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#1]
Fazer setup do ambiente de desenvolvimento local.

**Comment by diraol** [comment]
Done! =)
[ @vanessametonini se quiser colocar num arquivo de texto o passo a passo do que fizemos hoje seria legal =) ]

1h30

**Comment by vanessametonini** [comment]
### mac issues:

 adicionar linha no arquivo **~/.profile**  
    export PATH=/usr/local/bin:/usr/local/sbin:$PATH

```
$ brew install python
```

referência: http://docs.python-guide.org/en/latest/starting/install/osx/

**problema com instalação do python/pip (atualizar o openssl do mac)**  
http://stackoverflow.com/questions/15185661/update-openssl-on-os-x-with-homebrew

```
$ brew link --force openssl
```

### carceropolis local:

```
$ sudo pip install virtualenv

$ virtualenv venv

$ source venv/bin/activate

$ pip install -r requirements.txt
```

### depois das bibliotecas instaladas:

precisa do arquivo que não está no versionamento: **local_settings.py**

```
$ python manage.py createdb

$ python manage.py migrate

$ python manage.py runserver
```
