### ISSUE TITLE
[Infográfico][Saúde] Ajustes

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#100]
* [x] Corrigir o texto `Uma encarcerada pessoa tem` por `Uma pessoa encarcerada tem`;
* [x] Alinhar o texto "uma encarcerada pessoa tem" à esquerda;
* [x] Alinhar o texto "do que uma pessoa fora do sistema prisional." à esquerda.
* [x] Deixar em negrito PESSOA ENCARCERADA e PESSOA FORA DO SISTEMA PRISIONAL, seguindo a mesma linguagem usada no módulo Trabalho e Educação.

**Comment by vanessametonini** [comment]
Assim? 
![screen shot 2018-04-28 at 17 14 47](https://user-images.githubusercontent.com/3089882/39400491-b3df0db4-4b07-11e8-80b6-5aa93f01a1dd.png)
