### ISSUE TITLE
[Dados][Páginas Internas] Todas (modelo/base)

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#101]
* [ ] Ajustar breadcrumb para ficar na mesma linha que o 'submenu' de dados.

**Comment by vanessametonini** [comment]
Essa aqui acho que nao consigo fazer só com CSS... tenho que ver com calma como funciona os includes dos blocos no django...

**Comment by diraol** [comment]
Breadcrumb removido.
