### ISSUE TITLE
[Infográfico] Esconder barras de rolagem

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#103]
No Firefox aparecem as barras de rolagem vertical (sempre) e horizontal (de vez em quando, dependendo da largura da tela).

**Comment by vanessametonini** [comment]
Fiz uma alteração mas não consigo testar se deu certo, pq no meu SO nunca aparece barra de rolagem

**Comment by diraol** [comment]
Aqui resolveu!!!!!
