### ISSUE TITLE
[Unidades]

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#104]
* [x] Adicionar texto introdutório (produto da Thandara)
 * [x] @andresmrm  Colocar todos os elementos do mapa com a mesma cor (laranja carcerópolis);
 * [x] Trocar o ícone individual de uma unidade no mapa (ver referências da Ariane);
 * [x] Trocar o "X" que limpa o campo de busca por outro ícone (ex.: "vassoura" - fontawesome);
 * [x] `[ saiba mais ]` deve ficar acima do título "índices...";
 * [x] Apresentar "Índices" (título e conteúdos) apenas depois de clicar no "saiba mais";
 * [x] Ocultar tanto o card quanto o as informações de índices ao "fechar o card";
 * [x] Remover "link" de "Gestão da Unidade" (conteúdo);
 * [x] Ao lado dos dois títulos de índices colocar um símbolo de `?` (fontawesome) que leve a uma página com descrições de metodologia sobre os índices.
 * [x] @andresmrm  Removendo preenchimento dos "polígonos" quando passa o mouse.

**Comment by vanessametonini** [comment]
@diraol @hsvab já tem o texto introdutório?

**Comment by vanessametonini** [comment]
"Ao lado dos dois títulos de índices colocar um símbolo de ? (fontawesome) que leve a uma página com descrições de metodologia sobre os índices."
Tem o link dessa página já?

**Comment by vanessametonini** [comment]
Gente to com uma vaga lembrança que tinha que tirar esse saiba-mais também... pq ele não tem link pra nada... ou seria pra substituir ele pelo botão com o símbolo de interrogação, certo?
![unidades-saibamais](https://user-images.githubusercontent.com/3089882/39410630-9cbc57b6-4bd1-11e8-88ac-0535a855b294.png)

**Comment by diraol** [comment]
> Tem o link dessa página já?

Ainda não, mas pode colocar um "fake-link" que eu altero quando montar a outra página!

**Comment by diraol** [comment]
> Gente to com uma vaga lembrança que tinha que tirar esse saiba-mais também... pq ele não tem link pra nada... ou seria pra substituir ele pelo botão com o símbolo de interrogação, certo?

Isso, esse é para substituir por um ícone de "?" ao lado do número do índice.

**Comment by diraol** [comment]
@vanessametonini dá uma olhada nesse print:
![2018-05-03-080055_746x139_scrot](https://user-images.githubusercontent.com/192702/39573139-57f8d72e-4ea8-11e8-94d3-d9f57db96167.png)

A parte de "X pessoas / Y vagas" está quebrando a linha no lugar errado....

E acho que o `?` referente ao "índice de qualidade da informação" poderia ser um pouco menor e ficar logo à cima e à direita do valor do índice mesmo, algo um pouco mais discreto. (inclusive para ocupar menos espaço e evitar a quebra de linha que aconteceu (como pode ser visto no print). ;)

**Comment by diraol** [comment]
Mas as mudanças que você fez ficaram muito boas! =)
Ficou bem melhor!

Outro ponto, não havíamos conversado sobre outras cores para o gráfico de distribuição da população por raça/cor?

[Offtopic]
Nesse seu último commit, você colocou um "titulo" (`[Unidades] #104`), e uma descrição (o que vem a seguir). Só que para que o commit separe corretamente título de corpo, deveria haver uma linha em branco entre uma coisa e outra. Se você digitar `git log` vai perceber que ele "junta tudo" quando não há a linha em branco. ;)

**Comment by andresmrm** [comment]
Acho que arrumei os dois pontos em que estou marcado nessa issue. Vejam, por favor, se deu certo.

**Comment by hsvab** [comment]
@vanessametonini, ainda temos os mesmos problemas apontados pelo @diraol em 03/maio.

O valor de pessoas e a palavra 'pessoas' precisa caber na mesma linha.

![image](https://user-images.githubusercontent.com/2137923/41248268-db46ef92-6d86-11e8-8061-5712b2d0af89.png)

**Comment by hsvab** [comment]
@vanessametonini, aqui está o texto introdutório:

"Com 726.712 pessoas presas e um déficit de 358 mil vagas (INFOPEN, 2016), o
Brasil figura no ranking mundial como um dos países que mais encarcera
pessoas. Em um contexto de crescente encarceramento, as unidades prisionais
se apresentam como espaços superlotados, que não conseguem atender à
demanda de inclusão de pessoas, e onde se proliferam problemas de
infraestrutura que favorecem as reiteradas violações de direitos das pessoas
privadas de liberdade.
Nesta seção, serão analisados dados relativos às unidades prisionais, compostos
por um panorama geral sobre a população que se encontra nestes espaços,
informações gerais sobre gestão e acesso às unidades, além de informações
sobre a infraestrutura prisional e sua relação com a capacidade de garantir uma
vida digna às pessoas encarceradas. Mais do que avaliar a infraestrutura dos
estabelecimentos penais, o olhar sobre os espaços disponíveis relaciona-se
diretamente às políticas públicas que serão acessíveis à população privada de
liberdade e à qualidade dos serviços que serão prestados a esta população."
