### ISSUE TITLE
Personalizar design dos elementos do mapa

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#106]

**Comment by andresmrm** [comment]
Em https://github.com/ask-ar/carceropolis/commit/995a44644e969854dcefbfa9baed8ec2a5c62900 eu dei uma personalizada básica. Esse commit pode servir de referência para futuros ajustes.

Talvez seja melhor não mostrar a área quando dá hover, já que ela não tem muito significado. Para mudar isso é so descomentar a linha respectiva.

**Comment by hsvab** [comment]
Dá para personalizar por um símbolo de prisão (por exemplo o que é utilizado em 'infraestrutura')?

**Comment by andresmrm** [comment]
Dá sim. Vou ver isso.

**Comment by andresmrm** [comment]
Fiz a alteração. Mas acho que não ficou muito bom não... Talvez fique melhor sem a sombra?

**Comment by diraol** [comment]
De fato, melhor sem a sombra.
