### ISSUE TITLE
[Infográfico][Unidades Prisionais]

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#107]
Oi @vanessametonini , segue uma primeira versão de como deve ficar o "bloco Unidades Prisionais" lá na "Home de Dados".

[carceropolis_infografico_unidades.pdf](https://github.com/ask-ar/carceropolis/files/1898509/carceropolis_infografico_unidades.pdf)
![carceropolis_infografico_unidades](https://user-images.githubusercontent.com/192702/38613129-46af3314-3d5f-11e8-8917-f06f1af61aa2.png)

## Alterações
* [x] Trocar o texto "Existem 1422 Unidades prisionais" por "Há 1422 unidades prisionais". Se não couber numa única linha, talvez reduzir um pouco a fonte para tentar fazer caber numa linha só.
* [x] Seguindo a linguagem usada no bloco Situação Jurídica, deixar os destaques em vermelho (“49%”, “presos provisórios”, “11%” e “mais de 4 pessoas por vaga”) mas o restante do texto em branco.
* [x] Puxar uma "linha pontilhada" do 21% para a área do círculo respectiva (branca).
* [x] Colocar um `apenas` antes de 21% (se couber na mesma linha).
* [x] Em vez de `Em 11% das unidades prisionais do país, custodia-se mais de 4 pessoas por vaga`, o que achar de `Em 11% das unidades prisionais, custodia-se mais de 4 pessoas por vaga`. Talvez passe de 5 para 4 linhas.
* [x] Deixar o símbolo de feminino com linha cheia (branca, fina), ao invés de pontilhada.
* [x] Ajustar posicionamento das linhas direcionais (pontilhadas) do gráfico.

**Comment by diraol** [comment]
@vanessametonini vamos alterar algumas coisas nessa infografia, coloquei na descrição a lista de itens.

**Comment by vanessametonini** [comment]
![screen shot 2018-04-28 at 18 29 58](https://user-images.githubusercontent.com/3089882/39401020-3e0d3286-4b12-11e8-94e7-cd6da51b4166.png)

**Comment by diraol** [comment]
@vanessametonini a posição dos "pontilhados" ficou estranha aqui....
![2018-04-29-104714_1175x519_scrot](https://user-images.githubusercontent.com/192702/39407334-c8e495ce-4b9a-11e8-8bf0-78ea7c4934d5.png)

**Comment by diraol** [comment]
Corrigido.
