### ISSUE TITLE
[Infográfico][Perfil Populacional]

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#109]
* [x] Revisar o gráfico, que deve terminar em 2016.
* [x] Para evitar que o símbolo de feminino ao fundo não passe a impressão que o gráfico é referente apenas à população feminina, testar colocar o símbolo de masculino à esquerda do feminino.
* [x] Na parte com o mapa de São Paulo, trocar os blocos (texto e imagem) de lugar para facilitar a leitura do texto, deixando os dois textos próximos, no meio.

**Comment by diraol** [comment]
@vanessametonini ficaram ótimas as mudanças!

Mas nós, eu e a Haydée, acabamos nos desentendendo numa troca de emails e eu entendi errado o que ela havia comentado. (Além disso, o gráfico em si também estava errado).

Esse gráfico, para ficar compatível com o texto ao lado, deve ser o gráfico de evolução da população feminina.
O Gráfico (linha) que está lá é a evolução da população geral, apesar dos números no eixo à esquerda serem da população feminina.

Precisamos fazer o ajuste desse gráfico (eu tentei aqui, mas não deu **nada** certo.... fracasso total! rs).

Os dados são:

Ano | população
-- | --
2006 | 17216
2007 | 19034
2008 | 21604
2009 | 24292
2010 | 28188
2011 | 29347
2012 | 31824
2013 | 32882
2014 | 37380
2015 | 37380
2016 | 41087

Nesse sentido, realmente ficaremos apenas com o símbolo de "feminino" ao fundo. #myBad

**Comment by hsvab** [comment]
Precisamos fazer o ajuste desse gráfico com os seguintes dados:

Ano | população
-- | --
2009 | 24292
2010 | 28188
2011 | 29347
2012 | 31824
2013 | 32882
2014 | 33793
2015 | 37380
2016 | 38901
2017 | 36636
2018 | 34174
2019 | 34967

**Comment by diraol** [comment]
? @hsvab acho que você errou de repositório... era para serr no gitlab não?

**Comment by diraol** [comment]
Issue no gitlab -> https://gitlab.com/ASK-AR/conectas/carceropolis/-/issues/109
