### ISSUE TITLE
[Dados][Internas] Dados Gerais

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#111]
- [x] Texto Introdutório
    >  O Brasil ocupa o terceiro lugar no ranking mundial de encarceramento: só temos menos pessoas atrás das grades que Estados Unidos e China, nesta ordem. Ainda que muitos afirmem que a posição do país reflete seu número de habitantes, é importante notar que, entre essas nações que mais encarceram, somos a única em que a população prisional cresce mais do que a população total.
    > 
    > Por outro lado, exemplos como o da Índia, que tem pelo menos seis vezes mais habitantes, mas menos da metade da nossa população prisional, mostram que o encarceramento é fruto de escolhas políticas.
    > 
    > Entre os Estados, destaca-se a posição de São Paulo, que abriga mais de um terço (33%) de todos os presos do Brasil e registra a quarta maior taxa de encarceramento (número de presos por cada 100 mil habitantes) do país, de 536,5 [jun/2016]. A taxa nacional é de 352,6 [jun/2016].
    > 
    > A população prisional considerada pelo Levantamento de Informações Penitenciárias – Infopen é composta pela soma das populações custodiadas nas unidades prisionais do sistema penitenciário estadual (estabelecimentos penais geridos pelos estados ou por modelos de parceria entre a gestão estadual e entidades privadas, normalmente inseridos na estrutura das Secretarias de Justiça e Administração Prisional); as pessoas custodiadas em carceragens de delegacias ou outros espaços de custódia geridos pelos órgãos da segurança pública estadual; e as pessoas custodiadas nos 4 estabelecimentos penais do Sistema Penitenciário Federal, geridos diretamente pelo Departamento Penitenciário Federal. Os dados referentes às unidades do sistema penitenciário estadual e federal são informados diretamente pelos diretores ou responsáveis pelos estabelecimentos penais ao Departamento Página | 5Penitenciário Nacional e, assim, compõem as bases de dados abertos do Levantamento de Informações Penitenciárias - Infopen. Os dados referentes às pessoas custodiadas em carceragens de delegacias são coletados pela Secretaria Nacional de Segurança Pública – SENASP e repassados ao Departamento Penitenciário Nacional, para composição do relatório analítico do Infopen, mas não compõem as bases de dados abertos dos levantamentos. Não são consideradas no levantamento do Infopen as pessoas que cumprem pena em prisão albergue domiciliar e as pessoas monitoradas pelas Centrais de Monitoração Eletrônica. 
- [x] Gráfico 1
    - [x] **Título**
        - Taxa de encarceramento dos 4 países com a maior população prisional desde 2005.
    - [x] **Titulo do Eixo x**
        - Ano
    - [x] **Titulo do Eixo y**
        - Número de pessoas presas a cada 100 mil habitantes
    - [x] **Fonte**
        - [World Prision Brief, Institute for Criminal Policy Research.](http://www.prisonstudies.org/)
    - [x] **Notas**
        - A ONU possui indicador de referêncua da taxa máxima de encarceramento de 110 pessoas presas a cada 100 mil habitantes.
        - Os dados consideram a soma das populações custodiadas nas unidades prisionais do sistema penitenciário estadual (estabelecimentos penais geridos pelos estados ou por modelos de parceria entre a gestão estadual e entidades privadas, normalmente inseridos na estrutura das Secretarias de Justiça e Administração Prisional) e as pessoas custodiadas em carceragens de delegacias ou outros espaços de custódia geridos pelos órgãos da segurança pública estadual.
    - [x] **Dados**
        > Ano;EUA;China;Rússia;Brasil
        > 1992;501;;487;74
        > 1993;;;;
        > 1994;;;;
        > 1995;592;109;622;92
        > 1996;;;;
        > 1997;;;;102
        > 1998;655;115;688;
        > 1999;;;;
        > 2000;;;;
        > 2001;685;112;636;133
        > 2002;;;;
        > 2003;;;;
        > 2004;725;122;588;183
        > 2005;;;;
        > 2006;;;;
        > 2007;758;124;613;220
        > 2008;;;;
        > 2009;;;;
        > 2010;;123;609;253
        > 2011;;;;
        > 2012;707;;;287
        > 2013;;121;;
        > 2014;693;119;471;307
        > 2015;666;118;;
        > 2016;;;448;313
        > 2017;;;433;316
- [x] Gráfico 2
    - [x] **Título**
        - Evolução da população prisional brasileira
    - [x] **Titulo do Eixo x**
        - Ano
    - [x] **Titulo do Eixo y**
        - População carcerária (mil pessoas)
    - [x] **Fonte**
        - Ministério da Justiça; Levantamento de Informações Penitenciárias - Ministério da Justiça (2005 – 2016).
    - [x] **Notas**
        - Dados referentes ao mês de dezembro de cada ano, exceto para os anos de 2002 e 2016, em que o dado refere-se a junho.
        - Os dados consideram as pessoas custodiadas nas unidades do sistema prisional e nos espaços de custódia geridos pelos órgãos da segurança pública.
    - [x] **Dados**
        > Ano;População
        > 1990;90,0
        > 1991;
        > 1992;114,3
        > 1993;126,2
        > 1994;129,2
        > 1995;148,8
        > 1996;
        > 1997;170,6
        > 1998;
        > 1999;194,1
        > 2000;232,8
        > 2001;233,9
        > 2002;239,3
        > 2003;308,3
        > 2004;336,4
        > 2005;361,4
        > 2006;401,2
        > 2007;422,4
        > 2008;451,4
        > 2009;473,6
        > 2010;496,3
        > 2011;514,6
        > 2012;549,8
        > 2013;581,5
        > 2014;622,2
        > 2015;698,6
        > 2016;726,7
- [x] Gráfico 3
    - [x] **Título**
        - População prisional por Unidade da Federação
    - [x] **Titulo do Eixo x**
        - Número de pessoas presas
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - Os dados consideram as pessoas custodiadas nas unidades dos sistemas prisionais estadual e federal.
    - [x] **Dados**
        > Estado;População prisional
        > RR;1609
        > AP;2663
        > PI;3182
        > AC;4244
        > SE;4653
        > TO;5772
        > AL;5920
        > MA;6703
        > RN;7658
        > AM;8868
        > MT;10138
        > PB;10450
        > PA;12622
        > MS;13915
        > DF;14405
        > GO;15574
        > BA;15611
        > ES;16694
        > SC;16828
        > RO;17987
        > CE;21648
        > PE;26809
        > PR;28004
        > RS;28125
        > RJ;40301
        > MG;61392
        > SP;220030
        > BR;621805
- [x] Gráfico 4
    - [x] **Título**
        - Taxa de encarceramento
    - [x] **Titulo do Eixo x**
        - Número de pessoas presas a cada 100 mil habitantes
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho/2016. Pesquisa Nacional por Amostragem Domiciliar – PNAD/IBGE.
    - [x] **Notas**
    - [x] **Dados**
        > Estado;Taxa de encarceramento
        > MA;97
        > PI;99
        > BA;102
        > PA;153
        > AL;177
        > SE;205
        > RN;220
        > AM;230
        > GO;233
        > CE;241
        > RJ;242
        > SC;244
        > PR;249
        > RS;249
        > PB;263
        > PE;287
        > MG;293
        > MT;311
        > AP;343
        > RR;351
        > TO;379
        > ES;421
        > DF;485
        > SP;492
        > AC;529
        > MS;532
        > RO;101

**Comment by hsvab** [comment]
No gráfico "Taxa de encarceramento dos 4 países com a maior população prisional desde 2005", parte do gráfico dos EUA está atrás do box da legenda.
Reposicionar a legenda de forma que não oculte nenhuma parte das linhas dos gráficos.

**Comment by hsvab** [comment]
No gráfico "Taxa de encarceramento dos 4 países com a maior população prisional desde 2005", os valores de número de pessoas presas por 100mil hab estão com 2 casas decimais.
Corrigir valores para números inteiros (sem .00).

**Comment by hsvab** [comment]
No gráfico "Evolução da população prisional brasileira",  os valores de população carcerária (mil pessoas) estão com 2 casas decimais e notação americana.
Corrigir para ter apenas uma casa decimal e alterrar notação (usar , e não .).

**Comment by hsvab** [comment]
No gráfico "Evolução da população prisional brasileira", inserir nota explicativa sobre a descontinuidade do gráfico?

**Comment by hsvab** [comment]
No gráfico "População prisional por Unidade da Federação" avaliar se:
(i) apresentamos os valores do Número de Pessoas presas (eixo x) em (mil pessoas)
(ii) apresentamos as labels de valor nas barras

**Comment by hsvab** [comment]
No gráfico "População prisional por Unidade da Federação", os valores de número de pessoas presas estão com 2 casas decimais.
Corrigir valores para números inteiros (sem .00).

**Comment by hsvab** [comment]
No gráfico "Taxa de encarceramento por Unidade da Federação" avaliar se apresentamos as labels de valor nas barras.

**Comment by hsvab** [comment]
No gráfico "Taxa de encarceramento por Unidade da Federação", os valores de número de pessoas presas estão com 2 casas decimais.
Corrigir valores para números inteiros (sem .00).

**Comment by hsvab** [comment]
No gráfico "Taxa de encarceramento por Unidade da Federação", inserir link da fonte de dados da PNAD.

**Comment by hsvab** [comment]
- [ ] Gráfico 1 -  Taxa de encarceramento dos 4 países com a maior população prisional desde 2005
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Reposicionar a legenda de forma que não oculte nenhuma parte das linhas dos gráficos
  - [x] Corrigir valores de ordenada para números inteiros (sem .00)
  - [x] Apresentar no eixo x valores dos anos de 2 em 2, iniciando em 1992 e terminando em 2018

- [ ] Gráfico 2 - Evolução da população prisional brasileira
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Corrigir valores de ordenada para números com 1 casa decimal
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Apresentar no eixo x valores dos anos de 2 em 2, iniciando em 1990 e terminando em 2016
  - [x] Inserir nota explicativa sobre a descontinuidade do gráfico?

- [ ] Gráfico 3 - População prisional por Unidade da Federação
  - [ ] Avaliar se apresentamos as labels de valor nas barras
  - [x] Avaliar se apresentamos os valores do Número de Pessoas presas (eixo x) em (mil pessoas)
  - [x] Corrigir valores de abscissa para números inteiros (sem .00)
  - [x] Alterar título para "População prisional por UF"

- [ ] Gráfico 4 - Taxa de encarceramento por Unidade da Federação
  - [ ] Avaliar se apresentamos as labels de valor nas barras
  - [x] Corrigir valores de abscissa para números inteiros (sem .00)
  - [x] Inserir link da fonte de dados da PNAD
  - [x] Alterar título para "Taxa de encarceramento por UF"

**Comment by diraol** [comment]
Sobre o comentário do gráfico 2:

> Inserir nota explicativa sobre a descontinuidade do gráfico?

Concordo!
Proposta:

> As descontinuidades observadas no gráfico se devem a períodos nos quais o Ministério da Justiça não realizou o levantamento e a divulgação da respectiva informação.

**Comment by andresmrm** [comment]
Incorporei a sua proposta de nota, Diego.
