### ISSUE TITLE
[Dados][Internas] Perfil Populacional

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#112]
- [x] Texto Introdutório

> A população que se encontra atrás das grades no Brasil tem idade, cor, procedência e gênero. Embora tenhamos a terceira maior população prisional do mundo, a pequena variabilidade de perfis sócio demográficos entre a população prisional demonstra que existe uma parcela da população brasileira que compõe o alvo prioritário do Sistema de Justiça Criminal.
> 
> Os dados do Levantamento de Informações Penitenciárias – Infopen mostram que os jovens e as pessoas negras compõem, historicamente, a maior parcela da população prisional. As mulheres, por sua vez, representam o grupo populacional que, isoladamente, mais cresce dentro do sistema prisional, em uma curva de crescimento que não se compara à de nenhum dos países que mais encarceram no mundo.
> 
> Para formulação de dados sobre perfil da população prisional no Brasil são utilizados os dados do Infopen, que são informados diretamente pelos responsáveis pelas unidades prisionais ao Departamento Penitenciário Nacional. A maior parte das Página | 8informações sobre perfil são extraídas dos registros internos dos estabelecimentos penais sobre sua população e cadastradas pelos responsáveis, o que pode representar determinadas limitações metodológicas, especialmente quando se trata de informações que deveriam ser autodeclaradas pela pessoa privada de liberdade, como é o caso do gênero e da raça, cor ou etnia.

- [x] Gráfico 1
    - **Tipo do Gráfico**: Linha
    - [x] **Título**
        - População prisional por gênero
    - [x] **Fonte**
        - Levantamento Nacional de Informações Penitenciárias, Ministério da Justiça.
    - [x] **Notas**
        - Dados referentes a Dezembro de cada ano, exceto em 2016, que é referente a Junho.
    - [x] **Titulo do Eixo x**
        - Ano
    - [x] **Titulo do Eixo y**
        - Pessoas presas
    - [x] **Dados**
        > Ano;Homens;Mulheres
        > 2003;230340;9863
        > 2004;246237;16473
        > 2005;283994;12925
        > 2006;322364;17216
        > 2007;347325;19034
        > 2008;372094;21604
        > 2009;392820;24292
        > 2010;417517;28188
        > 2011;441907;29347
        > 2012;482073;31640
        > 2013;524404;32882
        > 2014;550965;33793
        > 2015;625775;37380
        > 2016;648860;41087
- [x] Gráfico 2
    - **Tipo do Gráfico**: Linha
    - [x] **Título**
        - Taxa de aprisionamento por gênero
    - [x] **Titulo do Eixo x**
        - Ano
    - [x] **Titulo do Eixo y**
        - Pessoas presas (por 100 mil habitantes)
    - [x] **Fonte**
        - Levantamento Nacional de Informações Penitenciárias, Ministério da Justiça. IBGE/Diretoria de Pesquisas. Coordenação de População e Indicadores Sociais. Gerência de Estudos e Análises da Dinâmica Demográfica. Projeção da população do Brasil e Unidades da Federação por sexo e idade para o período 2000-2030.
    - [x] **Notas**
        - Dezembro de cada ano. No caso do levantamento de 2016, refere-se a Junho.
    - [x] **Dados**
        > Ano;Homens;Mulheres
        > 2003;264,6;11,0
        > 2004;279,3;18,1
        > 2005;313,2;13,8
        > 2006;350,6;18,2
        > 2007;373,3;19,8
        > 2008;399,2;22,4
        > 2009;417,7;24,9
        > 2010;447,0;29,0
        > 2011;469,1;29,9
        > 2012;507,5;32,0
        > 2013;527,9;32,3
        > 2014;550,1;32,9
        > 2015;619,9;36,1
        > 2016;637,9;39,4
- [x] Gráfico 3
    - **Tipo do Gráfico**: Colunas
    - [x] **Título**
        - Raça/cor da população prisional
    - [x] **Titulo do Eixo x**
        - Raça/cor
    - [x] **Titulo do Eixo y**
        - Porcentagem de pessoas presas
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - No ano de 2016 foi informada raça/cor de apenas 127.563 pessoas presas em todo país.
    - [x] **Dados**
- [x] Gráfico 4
    - **Tipo do Gráfico**: Colunas (ou uma pirâmide etária segmentada por gênero)
    - [x] **Título**
        - População prisional por faixa etária
    - [x] **Titulo do Eixo x**
        - Faixa etária
    - [x] **Titulo do Eixo y**
        - Pessoas presas
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
    - [x] **Dados**

**Comment by diraol** [comment]
## Updated: Atualizei os dados com formato correto agora.

[03_raca_cor.zip](https://github.com/ask-ar/carceropolis/files/1974212/03_raca_cor.zip)
[04_faixa_etaria.zip](https://github.com/ask-ar/carceropolis/files/1974213/04_faixa_etaria.zip)

**Comment by diraol** [comment]
Atualizando dado do gráfico 03 (sem agrupar por UF)
[03_raca_cor.zip](https://github.com/ask-ar/carceropolis/files/1974143/03_raca_cor.zip)

**Comment by diraol** [comment]
[04_faixa_etaria.zip](https://github.com/ask-ar/carceropolis/files/1974186/04_faixa_etaria.zip)

**Comment by hsvab** [comment]
- [ ] Gráfico 1 - População prisional por gênero
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Reposicionar a legenda de forma que não oculte nenhuma parte das linhas dos gráficos
  - [x] Corrigir valores de ordenada para números inteiros (sem .00)
  - [x] Apresentar no eixo x valores de todos os anos: 2003, 2004, 2005, etc.


- [ ] Gráfico 2 - Taxa de aprisionamento por gênero
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Reposicionar a legenda de forma que não oculte nenhuma parte das linhas dos gráficos
  - [x] Corrigir valores de ordenada para números com 1 casa decimal
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Apresentar no eixo x valores de todos os anos: 2003, 2004, 2005, etc.
  - [ ] inserir link da fonte de dados do IBGE


- [ ] Gráfico 3 - Raça/cor da população prisional
  - [ ] Avaliar se apresentamos as labels de valor nas barras
  - [x] No csv disponibilizado: retirar a linha [total, 493236]
  - [x] No csv disponibilizado: corrigir título de "População" para "Porcentagem de pessoas presas"


- [ ] Gráfico 4 - População prisional por faixa etária
  - [ ] Avaliar se apresentamos as labels de valor nas barras
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Corrigir todos os "à" por "a" nos rótulos do eixo x e no csv
  - [x] No csv disponibilizado: retirar a linha [total, 515188.0]
  - [x] No csv disponibilizado: corrigir título de "População" para "Porcentagem de pessoas presas"

**Comment by diraol** [comment]
Haydée, com relação ao ponto:

 > Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado

Acho que não vai rolar, a biblioteca que estamos usando para gerar os gráficos demanda que o dado esteja formatado no padrão "americano". (mas no gráfico rola e já está feito).

Quer dizer... eu acho rs....

@andresmrm você confirma essa info minha? Ou podemos manter o CSV com "locale pt-br" tbm?

**Comment by andresmrm** [comment]
[2018-06-06 10:04] Diego Rabatone Oliveira:
> Haydée, com relação ao ponto:
> 
>     Usar locale brasileiro na formatação dos números tanto na apresentação do
>     gráfico quanto no csv disponibilizado
> 
> Acho que não vai rolar, a biblioteca que estamos usando para gerar os gráficos
> demanda que o dado esteja formatado no padrão "americano". (mas no gráfico rola
> e já está feito).

Acho que rola sim. Tem alguns CSVs onde os números estão entre aspas assim
"912,5" e o Pandas está interpretando direito. Seria só colocar todos nesse
formato. Vou cuidar disso.

**Comment by andresmrm** [comment]
No gráfico 2, qual seria o link da fonte de dados do IBGE?
