### ISSUE TITLE
[Dados][Internas] Infraestrutura

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#113]
- [x] Texto Introdutório

> Entre os diversos parâmetros que podem ser utilizados para medir a qualidade do tratamento oferecido às pessoas privadas de liberdade sob custódia do Estado, a situação de lotação dos estabelecimentos penais destaca-se como um dos principais. O artigo 88 da Lei de Execução Penal orienta que cada condenado deva ser alojado em cela individual, que contenha dormitório, aparelho sanitário e lavatório. Já as Regras Mínimas Para o Tratamento de Presos, produzidas pela ONU, afirmam que “As celas ou quartos destinados ao descanso noturno não devem ser ocupados por mais de um preso”. No mesmo sentido, as Regras Penitenciárias Europeias preconizam que a pessoa privada de liberdade deverá ser alojada, durante a noite, em cela individual, exceto se for considerado que lhe é mais favorável o alojamento com outras pessoas. Mais do que oferecer parâmetros inatingíveis ao poder público, estes instrumentos servem para delimitar os parâmetros de garantia da dignidade da pessoa privada de liberdade.
> 
> Os dados disponíveis sobre o sistema prisional brasileiro, no entanto, mostram que estes parâmetros estão distantes da realidade das pessoas que vivem atrás das grades no Brasil. Mais de 89% da população prisional no Brasil se encontra custodiada em estabelecimentos penais que têm mais pessoas do que vagas

- [x] Gráfico 1
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Taxa de ocupação por Unidade da Federação
    - [x] **Fonte**
        - Levantamento Nacional de Informações Penitenciárias, Ministério da Justiça.
    - [x] **Notas**
        - Não são consideradas as pessoas custodiadas em delegacias no cálculo do total da população prisional (e número de vagas) para composição da taxa de ocupação total, visto que essas informações não estão presentes nas bases de microdados disponibilizadas pelo DEPEN.
    - [x] **Titulo do Eixo x**
        - Taxa de ocupação (pessoas presas / vagas)
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 2
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Déficit de vagas por Unidade da Federação
    - [x] **Titulo do Eixo x**
        - Déficit de vagas
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - Não são consideradas as vagas e as pessoas custodiadas em delegacias no cálculo do total da população prisional (e número de vagas) para composição da taxa de ocupação total, visto que essas informações não estão presentes nas bases de microdados disponibilizadas pelo DEPEN.
    - [x] **Dados**

- [x] Gráfico 3
    - **Tipo do Gráfico**: barras
    - [x] **Título**
        - Relação entre entradas e saídas por Unidade da Federação
    - [x] **Titulo do Eixo x**
        - total de entradas / total de saídas
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - O número de entradas no sistema prisional considera o número de inclusões originárias (Inclusões não decorrentes de remoção ou transferência de outro estabelecimento do Sistema Prisional).
        - O número de saídas no sistema prisional considera a soma das saídas por alvarás de soltura (nesse caso, devem ser computados apenas os alvarás efetivamente cumpridos, que motivam a colocação da pessoa em liberdade), as fugas, os abandonos (não retorno em saída temporária) e os óbitos.
        - O Ministério da Justição não disponibiliza os dados referentes a fugas. 
    - [x] **Dados**

**Comment by diraol** [comment]
# Updated: Atualizei os dados com formato correto agora.
[01_ocupacao.zip](https://github.com/ask-ar/carceropolis/files/1974216/01_ocupacao.zip)
[02_deficit_vagas.zip](https://github.com/ask-ar/carceropolis/files/1974217/02_deficit_vagas.zip)
[03_coeficiente_entradas_saidas.zip](https://github.com/ask-ar/carceropolis/files/1974218/03_coeficiente_entradas_saidas.zip)

**Comment by andresmrm** [comment]
Eu vi que você reabriu essa issue, mas todos os pontos estão "checkados", falta algo?

**Comment by diraol** [comment]
Eu reabri porque pretendia adicionar mais um gráfico, mas não defini qual é o gráfico ainda.

**Comment by diraol** [comment]
[01_ocupacao.zip](https://github.com/ask-ar/carceropolis/files/2065185/01_ocupacao.zip)

Atualizando CSV (O anterior tinha algum erro nos dados, TO estava sem dado, p.ex.)

**Comment by hsvab** [comment]
- [ ] Gráfico 1 -  Taxa de ocupação por Unidade da Federação
  - [x] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Apresentar no eixo x valores de 0,5 em 0,5, iniciando em 0 e terminando em 4,5
  - [x] Rever dados porque falta dados de TO
  - [ ] Checar com Conectas/Thandara se é para considerarmos inclusive quem está em regime aberto no cálculo de taxa de ocupação. Se não formos considerá-las, inserir nota no gráfico.
  - [x] Alterar título para "Taxa de ocupação por UF"

- [x] Gráfico 2 - Déficit de vagas por Unidade da Federação
  - [x] Avaliar se apresentamos as labels de valor
  - [x] Corrigir valores de abcissa para números inteiros (sem .00)
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título para "Déficit de vagas por UF"
  - [x] Retirar nota "Não são consideradas as vagas e as pessoas custodiadas em delegacias no cálculo do total da população prisional (e número de vagas) para composição da taxa de ocupação total, visto que essas informações não estão presentes nas bases de microdados disponibilizadas pelo DEPEN."

- [x] Gráfico 3 - Relação entre entradas e saídas por Unidade da Federação
  - [x] Avaliar se apresentamos as labels de valor nas barras
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título da abcissa para "Coeficiente entradas / saídas"
  - [x] Rever formatação do eixo x: está aparecendo duas vezes o 1, o 2 e o 3.  
  - [x] Apresentar no eixo x valores dos anos de 0,5 em 0,5, iniciando em 0 e terminando em 3,0
  - [x] Alterar título para "Relação entre entradas e saídas por UF"

**Comment by hsvab** [comment]
- [x] Gráfico 4
    - Tipo do Gráfico: barras
  - [x] Título
    - Proporção de agentes em relação ao número de presos por Unidade da Federação
  - [x] Titulo do Eixo x
    - Quantidade de agentes por pessoas presas
  - [x] Titulo do Eixo y
    - Unidade da Federação
  - [x] Fonte
    - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
  - [x] Notas
    - A ONU apresenta como referência  a relação de 1 agente para cada 5 pessoas presas.
  - [x] Dados

**Comment by andresmrm** [comment]
Nos dados para gráfico 4 há as colunas "total_agentes","pop_total","proporcao". Era para ter só "proporcao", né? Se sim, me avisa que eu tiro as outras colunas aqui.

**Comment by diraol** [comment]
Ops, acho que esqueci o total ali. Pode remover sim "total_agentes" e "pop_total" sim!

**Comment by hsvab** [comment]
No Gráfico 4, penso ser melhor indicar no eixo horizontal as porcentagens. Por exemplo, ao invés de 0,05 indicar 5%.

**Comment by andresmrm** [comment]
[2018-06-11 14:18] hsvab:
> No Gráfico 4, penso ser melhor indicar no eixo horizontal as porcentagens. Por
> exemplo, ao invés de 0,05 indicar 5%.

Feito.

**Comment by diraol** [comment]
Pessoal, estou desfazendo essa última alteração (`0,05 -> 5%`) porque na realidade 5% é meio estranho, quando na realidade o número indica `0,05 agente para cada pessoa presa` (ou, temos 20 pessoas presas para cada agente).

**Comment by hsvab** [comment]
Perguntei pra Thandara no Telegram "no cálculo de taxa de ocupação (primeiro gráfico de infra - http://carceropolis.org.br/Dados/infraestrutura/) é para considerarmos inclusive total de pessoas inclusive quem está em regime aberto?"
