### ISSUE TITLE
[Dados][Internas] Situação Jurídica

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#114]
- [x] Texto Introdutório

> Os dados oferecidos pelo Infopen, do Ministério da Justiça, acerca da situação jurídica das pessoas privadas de liberdade, contemplam as seguintes categorias:
> 
> * Presos provisórios (ou sem condenação), que compreendem as pessoas privadas de liberdade que ainda não receberam decisão condenatória. Nesse caso, havendo sentença condenatória sobre determinada pessoa, ainda que não definitiva, os responsáveis pelo preenchimento do Infopen eram instruídos a não considerar esta pessoa provisória.
> * Presos sentenciados em regime fechado, que compreende as pessoas que receberam sentença transitada em julgado e cumprem pena em regime fechado.
> * Presos sentenciados em regime semiaberto.
> * Presos sentenciados em regime aberto.
> * Pessoas em cumprimento de medida de segurança de internação.
> * Pessoas em cumprimento de medida de segurança de tratamento ambulatorial.
> 
> Para composição do total de presos provisórios, no entanto, devem ser consideradas, além das informações que constam na base de dados do Infopen, também as pessoas que se encontram custodiadas em carceragens de delegacias ou outros espaços e custódia geridos pelos órgãos de segurança pública. Ainda que estes espaços não sejam adequados à custódia de pessoas, é preciso visibilizar a situação de aprisionamento destas pessoas.

- [x] Gráfico 1
    - **Tipo do Gráfico**: Barras agrupadas
    - [x] **Título**
        - Distribuição das incidências criminais por tipo penal entre homens e mulheres
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Titulo do Eixo x**
        - Pessoas presas (% por grupo de sexo)
    - [x] **Titulo do Eixo y**
        - Tipo penal
    - [x] **Dados**

- [x] Gráfico 2
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Percentual de presos sem condenação por Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - Não são consideradas as pessoas custodiadas em delegacias no cálculo do total da população prisional para composição da taxa de ocupação total pois essas informações não estão presentes nas bases de microdados disponibilizadas pelo DEPEN.
    - [x] **Titulo do Eixo x**
        - Pessoas sem condenação presas
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 3
    - **Tipo do Gráfico**: Gráfico de barras
    - [x] **Título**
        - % de unidades que receberam ao menos uma visita de inspeção dos órgãos nacionais e internacionais, por UF.
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
    - [x] **Titulo do Eixo x**
        - Percentual de Unidades da UF.
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

**Comment by diraol** [comment]
# Updated: Atualizei os dados com formato correto agora.
[01_incidencias_criminais_por_sexo.zip](https://github.com/ask-ar/carceropolis/files/1974220/01_incidencias_criminais_por_sexo.zip)
[02_percentual_presos_sem_condenacao.zip](https://github.com/ask-ar/carceropolis/files/1974221/02_percentual_presos_sem_condenacao.zip)

**Comment by diraol** [comment]
@andresmrm no gráfico 1 o dado é %. Mas no tooltip ele não aparece com o símbolo de "%" e, ainda por cima, está com ponto como separador de decimal e três dígitos decimais. Então "62,080%" fica "62.080", o que parece "sessenta e dois mil e oitenta". Acho que vale arredondar para duas casas decimais e, se der, colocar o "%" no tooltip tbm! ;)

**Comment by andresmrm** [comment]
[2018-05-04 21:36] Diego Rabatone Oliveira:
> [1]@andresmrm no gráfico 1 o dado é %. Mas no tooltip ele não aparece com o
> símbolo de "%" e, ainda por cima, está com ponto como separador de decimal e
> três dígitos decimais. Então "62,080%" fica "62.080", o que parece "sessenta e
> dois mil e oitenta". Acho que vale arredondar para duas casas decimais e, se
> der, colocar o "%" no tooltip tbm! ;)

Fiz o arredondamento e coloquei o %. Ainda estou vendo como fazer ele usar a
linguagem pt-BR (62.080,00 ao invés de 62,080.00).

**Comment by diraol** [comment]
[01_incidencias_criminais_por_sexo.zip](https://github.com/ask-ar/carceropolis/files/2029083/01_incidencias_criminais_por_sexo.zip)

Readicionando os dados do gráfico 1, agora com "Masculino", "Feminino" e "Total".

**Comment by diraol** [comment]
[03_percentual_unidades_com_visitacao.zip](https://github.com/ask-ar/carceropolis/files/2033179/03_percentual_unidades_com_visitacao.zip)

Dados do gráfico 03.

**Comment by andresmrm** [comment]
No primeiro gráfico, você passou novos dados incluindo o total, mas para plotar é para usar só masc e fem, né? Ou é para ter uma terceira barra em cada agrupamento mostrando o total?

**Comment by hsvab** [comment]
- [ ] Gráfico 1 -  Distribuição das incidências criminais por tipo penal entre homens e mulheres
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico (no csv está ok!)
  - [x] Alterar título do gráfico: retirar "entre homens e mulheres"
  - [x] Alterar título do eixo x para "Percentual de pessoas presas por sexo"
  - [x] Se for alterar a ordem de apresentação dos dados, checar posicionamento da legenda (pode ser que fique sobre alguma barra)

- [ ] Gráfico 2 - Percentual de presos sem condenação por Unidade da Federação
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título do gráfico para "Pessoas presas sem condenação por UF"
  - [x] Alterar título do eixo x para "Percentual de pessoas presas sem condenação"
  - [x] Retirar Nota "Não são consideradas as pessoas custodiadas em delegacias no cálculo do total da população prisional para composição da taxa de ocupação total pois essas informações não estão presentes nas bases de microdados disponibilizadas pelo DEPEN."

- [ ] Gráfico 3 - % de unidades que receberam ao menos uma visita de inspeção dos órgãos nacionais e internacionais, por UF
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título do gráfico para "Unidades prisionais que receberam ao menos uma visita de inspeção dos órgãos nacionais e internacionais por UF"
  - [x] Apresentar no eixo x valores percentuais de 10 em 10, iniciando em 0 e terminando em 100

**Comment by hsvab** [comment]
- [x] Gráfico 4
    - Tipo do Gráfico: barras agrupadas
  - [x] Título
    - Regimes de cumprimento de pena no Brasil
  - [x] Titulo do Eixo x
    - Quantidade de pessoas presas (por sexo)
  - [x] Titulo do Eixo y
    - Tipo de Regime
  - [x] Fonte
    - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
  - [x] Dados
