### ISSUE TITLE
[Dados][Internas] Trabalho e Educação

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#115]
- [x] Texto Introdutório

> O direto de acesso à assistência educacional e o direito de acesso ao trabalho são garantidos às pessoas privadas de liberdade através da Lei de Execução Penal - LEP.
> 
> Em relação à assistência educacional, a LEP prevê que o Estado deve oferecer instrução escolar e formação profissional, visando a reintegração da população prisional à sociedade. No levantamento do INFOPEN, as atividades educacionais são divididas entre atividades de ensino escolar, que compreendem a alfabetização e a formação escolar desde o ensino fundamental até o ensino médio, além dos cursos técnicos (caracterizados por uma carga horária mínima de 800 horas de aula) e o curso de formação inicial e continuada, que contempla a capacitação profissional e deve ser oferecido com carga horária mínima de 160 horas; e as chamadas atividades complementares, que compreendem os programas de remição pelo estudo por meio da leitura e demais atividades educacionais complementares (tais como: videoteca, atividades de lazer e cultura). As atividades de ensino formal dentro do ambiente prisional são oferecidas através do sistema estadual e municipal de ensino da localidade em que se encontra instalada a unidade prisional, sendo o ensino fundamental (ou ensino de 1o grau) de oferecimento obrigatório.
> 
> Em relação ao trabalho, a LEP prevê que o trabalho do condenado tenha finalidade educativa e produtiva. O trabalho das pessoas privadas de liberdade poderá ser realizado no interior da unidade prisional, para os casos de presos provisórios e condenados, ou fora do ambiente prisional, para os condenados que já tenham cumprido, pelo menos, 1/6 de sua pena total e que tenham obtido autorização expressa da direção do estabelecimento penal. As vagas de trabalho às quais as Página | 21 pessoas privadas de liberdade têm acesso podem ser oferecidas através de parcerias entre os órgãos da administração prisional e entidades ou empresas privadas, além de vagas de trabalho em serviços ou obras públicas oferecidas diretamente pela Administração Direta ou Indireta.
> 
> De modo geral, observa-se baixo acesso da população carcerária às vagas de trabalho e, nos casos em que há disponibilidade de vagas, observa-se baixa ou ausente remuneração recebida pelo trabalho desempenhado. Ainda que não esteja submetido ao regime da CLT, o trabalho das pessoas presas deve ser remunerado e esta remuneração deve obedecer ao limite mínimo de 3⁄4 do salário mínimo vigente, o que não é observado em grande parte dos estados

- [x] Gráfico 1
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Percentual de pressoas trabalhando, por Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
    - [x] **Titulo do Eixo x**
        - Número de pessoas presas trabalhando
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 2
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Percentual de pessoas que trabalham e recebem menos de 3/4 do salário mínimo, por UF
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - O percentual de pessoas que recebem menos de 3⁄4 do salário mínimo é calculado tendo como referência o número total de pessoas que trabalham e têm informação sobre remuneração recebida, conforme registrado pelos responsáveis pelo preenchimento do INFOPEN. Nesse sentido, esse percentual não se refere ao total de pessoas que trabalham no sistema prisional, pois nem sempre são apresentadas informações precisas sobre a existência ou não de remuneração.
    - [x] **Titulo do Eixo x**
        - Percentual de pessoas presas que trabalham e recebem menos de 3/4 do salário mínimo
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 3
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Percentual de pessoas estudando, por Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - O total de pessoas que estudam no sistema prisional compreende aquelas envolvidas em atividades de ensino escolar e em atividades complementares, em suas modalidades presencial ou à distância.
    - [x] **Titulo do Eixo x**
        - Percentual de pessoas presas estudando
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 4
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Escolaridade da população prisional brasileira, total e por Sexo
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
    - [x] **Titulo do Eixo x**
        - Grau de Instrução
    - [x] **Titulo do Eixo y**
        - Percentual de pessoas presas estudando
    - [x] **Dados**

**Comment by diraol** [comment]
# Updated: Atualizei os dados com formato correto agora.
[01_percentual_pessoas_trabalhando.zip](https://github.com/ask-ar/carceropolis/files/1974223/01_percentual_pessoas_trabalhando.zip)
[02_percentual_menos_de_34_de_SM.zip](https://github.com/ask-ar/carceropolis/files/1974224/02_percentual_menos_de_34_de_SM.zip)

**Comment by diraol** [comment]
(Os dados do Gráfico 2 ainda me soam estranhos e ainda vou revisá-los... parece haver algo de errado....)

**Comment by andresmrm** [comment]
Faltam também os dados do gráfico 3.

**Comment by diraol** [comment]
@andresmrm os dados do gráfico 3 eu ainda não consegui gerar.

Sobre o gráfico (2), o título não coube no espaço do gráfico ..... troquei `por Unidade da Federação` por `por UF`.

**Comment by diraol** [comment]
[03_percentual_pessoas_estudando.zip](https://github.com/ask-ar/carceropolis/files/1977106/03_percentual_pessoas_estudando.zip)

**Comment by diraol** [comment]
@andresmrm

**Comment by diraol** [comment]
@andresmrm 
[03_percentual_pessoas_estudando.zip](https://github.com/ask-ar/carceropolis/files/1977112/03_percentual_pessoas_estudando.zip)

**Comment by diraol** [comment]
[04_escolaridade.zip](https://github.com/ask-ar/carceropolis/files/2033345/04_escolaridade.zip)
Dados do gráfico 4!

**Comment by andresmrm** [comment]
Dá uma conferida nos dados do gráfico 4, por favor. Só tem porcentagens, faltam os "graus de instrução", não?

**Comment by diraol** [comment]
[04_escolaridade.zip](https://github.com/ask-ar/carceropolis/files/2065069/04_escolaridade.zip)

@andresmrm realmente, ficou faltando. Segue novamente agora corrigido! =)

Se quiser renomear algo pode mandar ver!

**Comment by hsvab** [comment]
- [ ] Gráfico 1 -  Percentual de pressoas trabalhando, por Unidade da Federação
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico como no csv
  - [x] Alterar título do gráfico para "Pessoas presas trabalhando por UF"
  - [x] Alterar título do eixo x para "Percentual de pessoas presas trabalhando"

- [ ] Gráfico 2 - Percentual de pessoas que trabalham e recebem menos de 3/4 do salário mínimo, por UF
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título do gráfico para "Pessoas presas que trabalham e recebem menos de 3/4 do salário mínimo por UF"
  - [x] Alterar título do eixo x para "Percentual de presas que trabalham e recebem menos de 3/4 do salário mínimo"
  - [x] Apresentar no eixo x valores percentuais de 10 em 10, iniciando em 0 e terminando em 100

- [ ] Gráfico 3 - Percentual de pessoas estudando, por Unidade da Federação
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título do gráfico para "Pessoas presas estudando por UF"
  - [x] Alterar título do eixo x para "Percentual de pessoas presas estudando"
  - [x] Apresentar no eixo x valores percentuais de 5 em 5, iniciando em 0 e terminando em 30

- [ ] Gráfico 4 - Escolaridade da população prisional brasileira, total e por Sexo
  - [ ] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números na apresentação do gráfico (csv está ok!)
  - [x] Alterar título do gráfico para "Escolaridade da população prisional brasileira"
  - [x] Alterar título do eixo x para "Percentual de pessoas presas por sexo"
  - [x] Apresentar no eixo x valores percentuais de 10 em 10, iniciando em 0 e terminando em 100
  - [x] Alterar título do eixo y para "Grau de instrução"

**Comment by diraol** [comment]
@hsvab, será que vale colocarmos notas nos gráficos 1, 2 e 3 dizendo que o RJ não forneceu informações sobre pessoas presas trabalhando e/ou estudando?

**Comment by diraol** [comment]
Revisar esse cálculo, o "Médio Completo Masculino" não faz sentido....
A soma, "por sexo", teria que dar 100% não?
(falando comigo mesmo)

**Comment by hsvab** [comment]
@diraol, acho que vale por essa nota nos Gráficos 1, 2 e 3 sim.

**Comment by hsvab** [comment]
No Gráfico 4, acho que deveríamos seguir o que fizemos nos outros gráficos:
-> soma das barras feminino = 100%
-> soma das barras masculino = 100%
.: revisar esse gráfico pq, de fato, não faz sentido os dados da categoria "Médio Completo"

**Comment by andresmrm** [comment]
[2018-06-11 14:27] hsvab:
> No Gráfico 4, acho que deveríamos seguir o que fizemos nos outros gráficos:
> -> soma das barras feminino = 100%
> -> soma das barras masculino = 100%

Como assim? Teria só duas barras? Uma masculino e outra feminino?

**Comment by diraol** [comment]
(Resolvi essa questão do gráfico 4)
