### ISSUE TITLE
[Dados][Internas] Saúde

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#116]
- [x] Texto Introdutório

> A Lei de Execução Penal prevê que os estabelecimentos penais no Brasil devam ser aparelhados para o oferecimento de atenção básica de saúde a todas as pessoas custodiadas, provisórias ou condenadas, e nos casos de média ou alta complexidade ou quando inexistir estrutura adequada para atendimento médico, a autoridade do estabelecimento penal deverá garantir que a pessoa privada de liberdade receba atendimento nos equipamentos de saúde pública da localidade.
> 
> Os dados coletados pelo levantamento do INFOPEN nos permitem analisar a capacidade dos estabelecimentos penais em oferecerem atendimento médico às pessoas custodiadas, a partir de dados de infraestrutura das unidades prisionais, além de abordarem a ocorrência de doenças e de mortes dentro do ambiente prisional. Quando comparamos os índices de prevalência de doenças transmissíveis e as mortes criminais ou naturais registradas no sistema prisional aos índices da população brasileira em geral, é possível identificar o papel desempenhado pelo contexto de aprisionamento na promoção de uma condição de vulnerabilidade das pessoas encarceradas, que se encontram submetidas a um ambiente em que se proliferam agravos transmissíveis, onde os índices de mortalidade são maiores que os observados nas ruas e, ao mesmo tempo, os índices de esclarecimento das mortes são ainda menores que os observados fora do ambiente prisional

- [x] Gráfico 1
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Taxa de pessoas com agravos transmissíveis por 10 mil pessoas presas, por UF
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - Os agravos transmissíveis considerados pelo levantamento do INFOPEN compreendem HIV, Sífilis, Hepatite, Tuberculose e Outros. O gráfico apresenta estas categorias agregadas.
    - [x] **Titulo do Eixo x**
        - Percentual da população prisional com agravo (por 10 mil habitantes)
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

(`total_agravos` * 10000)/  `poptotal_cominfoagravo` X `uf`
Sendo:
`total_agravos` = `hiv_masc` + `sifilis_masc` + `hepatite_masc` + `tuberculose_masc` + `outros_agravos_masc` + `hiv_fem` + `sifilis_fem` + `hepatite_fem` + `tuberculose_fem` + `outros_agravos_fem`

`poptotal_cominfoagravo`: Refere-se ao total da população custodiada apenas nas unidades que têm informação sobre agravos transmissíveis em seus registros. Nesse caso, deve ser considerada a população total [`poptotal_masc` + `poptotal_fem`] apenas para as unidades em que a variável `total_agravos` seja diferente de blank.

- [x] Gráfico 2
    - **Tipo do Gráfico**: Barras empilhadas
    - [x] **Título**
        - Óbitos no sistema prisional, por Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
    - [x] **Titulo do Eixo x**
        - Total de óbitos
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**
- [x] Gráfico 3
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Taxa de óbitos por 10 mil pessoas presas, por UF
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - No levantamento do INFOPEN de 2016, o estado do Rio de Janeiro não ofereceu dados sobre o número de mortes registradas no sistema prisional e, assim, a população deste estado não foi considerada no cálculo das taxas nacionais.
    - [x] **Titulo do Eixo x**
        - Taxa de óbitos por 10 mil habitantes
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 4
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Relação entre profissionais de saúde e pessoas presas, por Unidade da Federação
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - Referência para padrão exigido de 1 para 500
    - [x] **Titulo do Eixo x**
        - Profissionais de saúde para cada 500 presos
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

**Comment by diraol** [comment]
[02_taxa_obitos.zip](https://github.com/ask-ar/carceropolis/files/1981954/02_taxa_obitos.zip)

**Comment by diraol** [comment]
Gente, alguém conseguiu entender direito aquela explicação sobre `poptotal_cominfoagravo`?
c/c @hsvab e @andresmrm

**Comment by andresmrm** [comment]
Essa?

> (poptotal_cominfoagravo): Refere-se ao total da população custodiada apenas nas unidades que têm informação sobre agravos transmissíveis em seus registros. Nesse caso, deve ser considerada a população total [(poptotal_masc) + (poptotal_fem)] apenas para as unidades em que a variável (total_agravos) seja diferente de blank.
> Nota: Os agravos transmissíveis considerados pelo levantamento do INFOPEN compreendem HIV, Sífilis, Hepatite, Tuberculose e Outros. O gráfico apresenta estas categorias agregadas.

Que dúvida você teve? Não é simplesmente ignorar as unidades das quais não temos essa informação?

**Comment by diraol** [comment]
Essa mesmo @andresmrm .....
Acho que o que me deixou um pouco confuso foi:

> Nesse caso, deve ser considerada a população total [(poptotal_masc) + (poptotal_fem)] apenas para as unidades em que a variável (total_agravos) seja diferente de blank.

**Comment by diraol** [comment]
[03_obitos_sistema_prisional.zip](https://github.com/ask-ar/carceropolis/files/2037597/03_obitos_sistema_prisional.zip)

**Comment by diraol** [comment]
[04_relacao_funcionarios_pessoas_presas.zip](https://github.com/ask-ar/carceropolis/files/2041643/04_relacao_funcionarios_pessoas_presas.zip)

**Comment by andresmrm** [comment]
Não entendi o gráfico 4...
"% de profissionais de saúde para cada 500 presos", aqui fala de uma porcentagem (que já é meio estranha, porque é em 500)
"Referência para padrão exigido de 1 para 500" e aqui fala de um valor absoluto...

No gráfico 3 são barras empilhadas mesmo? Fiz barras simples, pois foi o que entendi dos dados.

**Comment by diraol** [comment]
De fato, você tem razão sobre o gráfico 4.

Fiz a devida alteração no texto descritivo do eixo. Veja se agora faz mais sentido. =)

**Comment by andresmrm** [comment]
Melhorou! Vlw!

**Comment by diraol** [comment]
Sobre o gráfico 3, de fato, fiz confusão com as coisas.... Segue agora de forma que dê para empilhar! =)
[03_obitos_sistema_prisional.zip](https://github.com/ask-ar/carceropolis/files/2065125/03_obitos_sistema_prisional.zip)

**Comment by hsvab** [comment]
- [ ] Gráfico 2 - Taxa de óbitos por 10 mil pessoas presas, por UF
  - [x] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título do gráfico para "Taxa de óbitos por 10 mil pessoas presas por UF"
  - [x] Alterar título do eixo x para "Taxa de óbitos por 10 mil pessoas presas"
  - [x] Apresentar no eixo x valores percentuais de 5 em 5, iniciando em 0 e terminando em 45

- [ ] Gráfico 3 - Óbitos no sistema prisional, por Unidade da Federação
  - [x] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números na apresentação do gráfico (csv está ok!)
  - [x] Corrigir valores de ordenada para números inteiros (sem .00)
  - [x] Alterar título do gráfico para "Óbitos no sistema prisional por UF"
  - [x] Apresentar no eixo x valores de 50 em 50,  iniciando em 0 e terminando em 450

- [ ] Gráfico 4 - Relação entre profissionais de saúde e pessoas presas, por Unidade da Federação
  - [x] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título do gráfico para "Relação entre profissionais de saúde e pessoas presas por UF"
  - [x] Alterar título do eixo x para "Profissionais de saúde para cada 500 pessoas presas"
  - [x] Apresentar no eixo x valores percentuais de 5 em 5, iniciando em 0 e terminando em 20
  - [ ] Rever redação da Nota "Referência para padrão exigido de 1 para 500"

**Comment by hsvab** [comment]
Eu inverteria os gráficos 2 e 3 na ordem da página.

**Comment by hsvab** [comment]
@diraol Sobre o cálculo do poptotal_cominfoagravo, entendo que é para selecionar e desconsiderar casos em que todas as variáveis sobre agravos forem NA ao mesmo tempo e só então fazer o total.

**Comment by diraol** [comment]
> Eu inverteria os gráficos 2 e 3 na ordem da página.

Invertidos (no primeiro post, não reenviei os dados nem alterei mais nada em lugar nenhum ainda).

**Comment by diraol** [comment]
@hsvab 
Fiquei pensando no gráfico "Taxa de óbito por 10 mil pessoas presas. Será que isso não pode trazer algum problema ou erro por termos (10) estados que não tem 10 mil pessoas presas?

**Comment by diraol** [comment]
Sobre o gráfico de números absolutos de óbitos por UF (separados por "tipo").
Pensei em ordená-lo por "óbitos do tipo criminal", em ordem decrescente, destacando os estados com maiores índices nesse quesito. O que acham?

**Comment by diraol** [comment]
Outra coisa, ainda sobre o número absoluto de óbitos.

O número de suicídios em SP me chamou a atenção. Mas fico me perguntando até que ponto não é decorrência da diferença de tamanho das populações prisionais dos estados.
Será que faria sentido fazermos esse gráfico ("óbitos por tipo") proporcional ao total de óbitos da UF?

**Comment by diraol** [comment]
Rever também, nos gráficos sobre óbitos, se precisamos adicionar notas sobre o Estado de RR, assim como fizemos para o RJ no gráfico de taxa de óbitos, pois parece não ter dado para RR nos dois gráficos.

**Comment by hsvab** [comment]
@diraol , sobre (gráfico 3 agora):
>Fiquei pensando no gráfico "Taxa de óbito por 10 mil pessoas presas. Será que isso não pode trazer algum problema ou erro por termos (10) estados que não tem 10 mil pessoas presas?

Não vejo problema porque é uma métrica que está claramente descrita.
No mais, checa esse dado do Rio - a taxa de óbito é baixa mesmo ou não deram infos?

**Comment by hsvab** [comment]
@diraol, sobre (gráfico 2):
>O número de suicídios em SP me chamou a atenção. Mas fico me perguntando até que ponto não é decorrência da diferença de tamanho das populações prisionais dos estados.
Será que faria sentido fazermos esse gráfico ("óbitos por tipo") proporcional ao total de óbitos da UF?

Olhando o gráfico resultante pensei nisso tb. Acho que os tamanhos de população distorcem a leitura... Vamos tentar um propocional então. Bora @andresmrm ?

**Comment by hsvab** [comment]
@diraol, ainda sobre gráfico 2:
> Sobre o gráfico de números absolutos de óbitos por UF (separados por "tipo").
Pensei em ordená-lo por "óbitos do tipo criminal", em ordem decrescente, destacando os estados com maiores índices nesse quesito. O que acham?

Acho que podemos falar com o Leonardo e vermos por qual categoria ele prefere ordenar. Depois de termos feito o proporcional.

**Comment by hsvab** [comment]
> Rever também, nos gráficos sobre óbitos, se precisamos adicionar notas sobre o Estado de RR, assim como fizemos para o RJ no gráfico de taxa de óbitos, pois parece não ter dado para RR nos dois gráficos.

De acordo!

**Comment by andresmrm** [comment]
[2018-06-11 14:36] hsvab:
> Olhando o gráfico resultante pensei nisso tb. Acho que os tamanhos de população
> distorcem a leitura... Vamos tentar um propocional então. Bora [2]@andresmrm ?
Você quer dizer um X óbitos por Y habitantes?
Fiz um por 100 mil habitantes. Vejam se é isso mesmo, e dai atualizamos as
legendas.
