### ISSUE TITLE
[Dados][Internas] Materno Infantil

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#117]
- [x] Texto Introdutório

> A legislação brasileira prevê que mulheres gestantes e mães de crianças de até 12 anos de idade incompletos, que ainda não foram julgadas, podem ter sua prisão preventiva convertida em prisão domiciliar, o que garantiria a manutenção do vínculo da mãe com a criança, no ambiente doméstico, até a condenação transitada em julgado . A medida se alinha a tratados internacionais assinados pelo Brasil, tais como as Regras de Bangkok da ONU , que abordam as especificidades do exercício da maternidade no ambiente prisional a trazem à tona um debate sobre as diferentes violações de direitos que podem ocorrer ao longo processo gestacional da mulher privada de liberdade, no período da amamentação e, posteriormente, no afastamento entre a mãe a criança.
> 
> Ao longo do período gestacional, a mulher privada de liberdade está submetida a uma maior dificuldade de acesso ao atendimento pré-natal, quando comparada às usuárias do sistema público de saúde, e pode estar sujeita a agressões (física, verbal ou psicológica) no momento do parto.
> 
> No período da amamentação, o direito ao aleitamento materno está ameaçado para as mulheres privadas de liberdade pela inexistência de espaços adequados para amamentação no ambiente prisional.
> 
> Após o período da amamentação, tem início o processo de afastamento da criança, que costuma ocorrer entre os 6 meses e 1 ano de idade, quando os laços com a mãe são rompidos e a criança é entregue à família da mulher presa, quando esta puder ser identificada, ou é encaminhada para serviços de abrigamento, onde permanecerá, muitas vezes sem qualquer contato com a mãe, até que seja encaminhada à adoção. Os dados disponíveis sobre o sistema prisional brasileiro permitem identificar a ausência de estruturas de creche, berçários e celas adaptadas para gestantes ou lactantes no ambiente prisional, compondo um cenário em que as mulheres privadas de liberdade, em sua maioria jovens, são submetidas a um ambiente que, por um lado, aprofunda sua vulnerabilidade no contexto da maternidade e, por outro, estende a execução da pena privativa de liberdade aos seus filhos.

- [x] Gráfico 1
    - **Tipo do Gráfico**: Barras empilhadas (somam 100%)
    - [x] **Título**
        - Percentual de gestantes e lactantes em unidades com e sem berçário e/ou Centro de Referência à Saúde Materno-Intanfil, por UF.
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - Berçários são seções próprias dos estabelecimentos penais, destinados a bebês com até dois anos de idade. Os Centros de Referência à Saúde Materno-Infantil são unidades de saúde feminina que incorporam serviços de assistência à gestante, parturiente, nutriz e seus respectivos filhos, asegurando acompanhamento médico à mulher, principalmente no pré-natal e no pós-parto, extensivo ao recém-nascido. No gráfico acima foram consideradas apenas as unidades prisionais femininas e mistas.
    - [x] **Titulo do Eixo x**
        - Percentual de gestantes ou lactantes
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 2
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Número total de crianças presentes nos estabelecimentos penais, por UF.
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - O gráfico considera o número total de crianças presentes nos estabelecimentos penais femininos ou mistos, independente da faixa etária, que pode ser de 0 a 7 anos, conforme estabelecido na Lei no 11.942, de 28 de maio de 2009.
    - [x] **Titulo do Eixo x**
        - Número total de crianças
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

**Comment by diraol** [comment]
[01_percentual_gestantes.zip](https://github.com/ask-ar/carceropolis/files/1981951/01_percentual_gestantes.zip)

**Comment by diraol** [comment]
[02_total_criancas.zip](https://github.com/ask-ar/carceropolis/files/1985993/02_total_criancas.zip)

**Comment by hsvab** [comment]
- [x] Gráfico 1 - Percentual de gestantes e lactantes em unidades com e sem berçário e/ou Centro de Referência à Saúde Materno-Intanfil, por UF.
  - [x] Corrigir tipo de gráfico para barras empilhadas somando 100%, separando em 2 categorias: "Com Berçário e/ou CRSMI" e "Sem Berçário e/ou CRSMI"
  - [x] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números tanto na apresentação do gráfico quanto no csv disponibilizado
  - [x] Alterar título do gráfico para "Gestantes e lactantes em unidades com e sem berçário e/ou Centro de Referência à Saúde Materno-Intanfil por UF"
  - [x] Alterar título do eixo x para "Percentual de gestantes e lactantes por disponibilidade de berçário e/ou CRSMI"
  - [x] Apresentar no eixo x valores percentuais de 10 em 10, iniciando em 0 e terminando em 100
  - [x] Colocar como 2º gráfico

- [x] Gráfico 2 - Número total de crianças presentes nos estabelecimentos penais, por UF.
  - [x] Avaliar se apresentamos as labels de valor
  - [x] Usar locale brasileiro na formatação dos números na apresentação do gráfico (csv está ok!)
  - [x] Corrigir valores de ordenada para números inteiros (sem .00)
  - [x] Alterar título do gráfico para "Presença de crianças na unidades prisionais por UF"
  - [x] Alterar título do eixo x para "Total de crianças "
  - [x] Apresentar no eixo x valores de 100 em 100.
  - [x] Colocar como 3º gráfico

**Comment by hsvab** [comment]
- [x] Gráfico 3
    - Tipo do Gráfico: barras
   - [x] Título
    - Mulheres grávidas e lactantes por UF
  - [x] Titulo do Eixo x
    - Quantidade de gestantes e lactantes
  - [x] Titulo do Eixo y
    - Unidade da Federação
  - [x] Fonte
    - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
  - [x] Dados
  - [x] Colocar como 1º gráfico

**Comment by hsvab** [comment]
- [x] Gráfico 4
    - Tipo do Gráfico: barras
   - [x] Título
    - Disponibilidade de celas adequadas para gestante por UF
  - [x] Titulo do Eixo x
    - Percentual de unidades femininas ou mistas com celas adequadas para gestante
  - [x] Titulo do Eixo y
    - Unidade da Federação
  - [x] Fonte
    - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
  - [x] Notas:
    -  No gráfico acima foram consideradas apenas as unidades prisionais femininas e mistas.
  - [x] Dados

Cáclulo:
-> Filtar unidades femininas ou mistas
  -> Marcador de se a unidade tem ou não cela para gestante
    -> Total de unidades com cela para gestante / total de unidads femininas ou mistas
