### ISSUE TITLE
[Dados][Internas] Alas Exclusivas

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#118]
- [x] Texto Introdutório

> O reconhecimento da diversidade no ambiente prisional e a formulação de políticas que atentem para as especificidades de determinados grupos populacionais vulneráveis visibilizam as subjetividades dos indivíduos criminalizados e valorizam as diferenças como ferramenta para a promoção da igualdade e garantia de direitos humanos fundamentais. Ainda que o conjunto da população prisional possa parecer um todo homogêneo por um olhar sobre seu perfil demográfico, há grupos que requerem cuidados diferenciados e demandam ações específicas da administração prisional, como é o caso das pessoas com deficiência física, que requerem instalações adaptadas, ou as pessoas que sofrem maiores preconceitos na sociedade por conta de sua orientação sexual e identidade de gênero e que, dentro do ambiente prisional, podem ser expostas a agressões (físicas, sexuais ou psicológicas) e, portanto, demandam que o estado ofereça condições de cumprimento da pena em condição de igualdade aos demais grupos e minimize os riscos que se apresentam contra aquele grupo específico.
> 
> Nesse sentido, os dados hoje disponíveis acerca do sistema prisional brasileiro nos permitem um olhar sobre a infraestrutura prisional e sua capacidade de oferecer espaços exclusivos para grupos populacionais marcados por sua orientação sexual e identidade de gênero, geração, nacionalidade e condição de deficiência, como parte de uma política de atenção à diversidade que se mostra ainda incipiente no sistema prisional.

- [x] Gráfico 1
    - **Tipo do Gráfico**: barras
    - [x] **Título**
        - Percentual de unidades que contam com ala/cela exclusiva para população LGBT, por UF
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - O gráfico acima considera as unidades que contam seções ou módulos autônomos, incorporados ou anexos aos estabelecimentos, ou celas exclusivas destinadas a abrigar pessoas que se identifiquem como lésbicas, gays, bissexuais, travestis e transexuais (LGBT) e que estejam privadas de liberdade.
    - [x] **Titulo do Eixo x**
        - Percentual de unidades com ala/cela exclusiva para população LGBT
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 2
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Percentual de unidades que contam com ala/cela exclusiva para população idosa, por UF
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - O gráfico acima considera as unidades que contam seções ou módulos autônomos, incorporados ou anexos aos estabelecimentos, ou celas exclusivas destinadas a abrigar pessoas presas que tenham no mínimo 60 anos de idade ao ingressarem ou os que completem essa idade durante o tempo de privação de liberdade.
    - [x] **Titulo do Eixo x**
        - Percentual de unidades com ala/cela exclusiva para população Idosa
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 3
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Percentual de unidades que contam com ala/cela exclusiva para população indígena, por UF
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - O gráfico acima considera as unidades que contam seções ou módulos autônomos, incorporados ou anexos aos estabelecimentos, ou celas exclusivas destinadas a abrigar as pessoas indígenas privadas de liberdade.
    - [x] **Titulo do Eixo x**
        - Percentual de unidades com ala/cela exclusiva para população estrangeira
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 4
    - **Tipo do Gráfico**: Barras
    - [x] **Título**
        - Percentual de unidades que contam com ala/cela exclusiva para população estrangeira, por UF
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - O gráfico acima considera as unidades que contam seções ou módulos autônomos, incorporados ou anexos aos estabelecimentos, ou celas exclusivas destinadas a abrigar as pessoas estrangeiras privadas de liberdade.
    - [x] **Titulo do Eixo x**
        - Percentual de unidades com ala/cela exclusiva para população estrangeira
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

- [x] Gráfico 5
    - **Tipo do Gráfico**: 
    - [x] **Título**
        - Percentual de pessoas com deficiência física que estão em unidades não adaptadas, por UF
    - [x] **Fonte**
        - Levantamento de Informações Penitenciárias - Ministério da Justiça, Junho de 2016.
    - [x] **Notas**
        - No levantamento do Infopen, entende-se a adaptação das unidades como o estabelecimento de condições e possibilidades de alcance para utilização, com segurança e autonomia, de edificações, seus espaços, mobiliários e equipamentos, proporcionando às pessoas com deficiência a maior independência possível e aumento das condições de realização das mesmas atividades que as demais pessoas. A condição de acessibilidade das unidades prisionais é medida de acordo com a aderência aos parâmetros estabelecidos pela Norma Brasileira ABNT n. 9050, de 2004.
    - [x] **Titulo do Eixo x**
        - Percentual de pessoas com deficiência física em unidades não adaptadas
    - [x] **Titulo do Eixo y**
        - Unidade da Federação
    - [x] **Dados**

**Comment by diraol** [comment]
[01_percentual_ala_cela_lgbt.zip](https://github.com/ask-ar/carceropolis/files/2042766/01_percentual_ala_cela_lgbt.zip)
[02_percentual_ala_cela_idosos.zip](https://github.com/ask-ar/carceropolis/files/2042767/02_percentual_ala_cela_idosos.zip)
[03_percentual_ala_cela_indigenas.zip](https://github.com/ask-ar/carceropolis/files/2042768/03_percentual_ala_cela_indigenas.zip)
[04_percentual_ala_cela_estrangeiros.zip](https://github.com/ask-ar/carceropolis/files/2042769/04_percentual_ala_cela_estrangeiros.zip)

**Comment by diraol** [comment]
Para o gráfico 5, fiz o seguinte cálculo:
1) Para cada unidade prisional:
  - `déficit de vagas adaptadas` = `soma de pessoas presas com deficiência física` - `soma de vagas adaptadas`
2) Agrupar por Estado (UF)
3) Para cada UF:
  - `taxa` = `soma de déficit de vagas adaptadas` / `soma de pessoas com deficiência física`

Então acho que vale alterar o título/descrição do gráfico para:
Título: `Percentual de pessoas com deficiência física não assistidas por vagas adaptadas, por UF` ou `Déficit de vagas adaptadas para pessoas com deficiência física, por UF`.

O mesmo vale para o título do eixo X.

**Comment by hsvab** [comment]
@diraol, sobre gráfico 5, prefiro o título "Percentual de pessoas com deficiência física não assistidas por vagas adaptadas por UF"

**Comment by andresmrm** [comment]
[2018-06-11 14:44] hsvab:

> [1]@diraol, sobre gráfico 5, prefiro o título "Percentual de pessoas com
> deficiência física não assistidas por vagas adaptadas por UF"

Arrumei o título.
