### ISSUE TITLE
Usar locale brasileiro na formatação dos números dos gráficos

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#119]
Parece que o Bokeh não consegue fazer isso facilmente.
Uma opção seria usar o `CustomJSHover` do Bokeh para implementar isso na mão em JS como sugerido aqui:
https://github.com/bokeh/bokeh/issues/7903#issuecomment-388977267
Outra seria já formatar os dados em Python antes de enviar.

Não sei se essas opções funcionam para os ticks do gráfico (valores que aparecem nos eixos)

**Comment by diraol** [comment]
Hum.....

Só vendo se eu entendi direito.
Temos que "corrigir" a apresentação em dois lugares diferentes:

 1. Eixo do gráfico;
 2. Tooltip de hover;

Para corrigir no "eixo do gráfico", precisaríamos modificar o `NumeralTickFormatter`, mas ele não resolve o `Hover`.

Para corrigir o `Hover`, ou usamos o `CustomJSHover` ou modificamos os dados antes de enviar ao browser.
No caso de modificarmos, se transformarmos em "dado" para a "formatação desejada" precisaríamos que ele fosse enviado como "texto" ao navegador, o que não serviria para fazer o "plot". Então talvez fosse necessário adicionar uma nova coluna com o "número convertido em texto formatado".
É isso?

Me parece que essa opção de alterar no "backend" vai mais dificultar que ajudar, já que demandaria fazer essa modificação para cada gráfico, enquanto "resolver" o `NumeralTickFormatter` e o `CustomJSHover` seriam soluções mais genéricas.

Entendi direito? Faz sentido o que eu disse?

**Comment by andresmrm** [comment]
Você colocou um ponto que eu não tinha pensando. Teríamos que converter os números para texto para obrigá-lo a usar a nossa formatação. E acho que daí quebraria os gráficos, porque texto é plotado de maneira diferente de números. Logo acho que a única saída é via JS.

Eles comentam nas issues algo sobre incluir o arquivo de línguas do Numbro para fazer funcionar. Mas aqui não deu certo, e também não faz muito sentido para mim. Perguntei lá para eles como faz. Vamos ver se respondem.

**Comment by andresmrm** [comment]
Parece que o pessoal do Bokeh não está sabendo como formatar para outras línguas via o sistema que eles montaram, mas me passaram umas dicas de como colocar JS diretamente para fazer a formatação eu mesmo.

Estou usando por enquanto o [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) que já vem padrão no JS, mas não suporta alguns navegadores mais antigos. Vejam se acham ok.

Eu ia usar o Numbro, que é o mesmo que o Bokeh usa, mas parece que está com um bug justamente no suporte a outras línguas. Os gringos não usam essa funcionalidade, então está bugado nas duas libs...

**Comment by diraol** [comment]
Oi Andrés!

Então, como nosso foco é desktop mesmo, acho que vale seguir com o toLocaleString! =)
Valeu ai pela pesquisa e pelo esforço!
Ps.: Maldito seja o "não-padrão-internacional".....

**Comment by diraol** [comment]
Ficou ótimo! Valeu!
