### ISSUE TITLE
Ordenar dados dos gráficos?

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#120]
Por enquanto os gráficos em barras estão colocando as barras na mesma ordem em que estão nos dados (acho). Isso nos deixa controlar manualmente a ordem.

Outra opção é ordenar automaticamente, seja pelo tamanho da barra, seja por ordem alfabética da legenda. Pelo que me lembro nem sempre a mesma ordem faz sentido para todos os gráficos.

**Comment by hsvab** [comment]
Acho uma boa questão para fecharmos com a Conectas, mas tendo a achar que ordenar pelo "tamanho da barra" é o que pode ser mais interesante ao leitor.

**Comment by diraol** [comment]
Faz sentindo...
Aliás, estou aproveitando essa issue aqui para subir todos os dados "atualizados" (nem todos foram necessariamente modificados, mas muitos foram. Além dos novos gerados. Assim, ao invés de subir eles individualmentes em cada issue achei mais fácil compartilhar o "pacote quase completo" por aqui.
[dados_2018_06_04_00h_20m.zip](https://github.com/ask-ar/carceropolis/files/2066751/dados_2018_06_04_00h_20m.zip)

**Comment by andresmrm** [comment]
Ok, então espero a resposta da Conectas.

Sobre os dados, a atualização deles vai acontecer outras vezes? Porque por enquanto preciso reformatá-los e colocar de novo os metadados na mão. Mas se for para ficar repetindo o processo seria melhor automatizar. Aguardo sua resposta para saber como faço já dessa vez.

**Comment by diraol** [comment]
@andresmrm conversei aqui com a Haydée não sei exatamente quando vamos conseguir ver essa questão com a Conectas, então decidimos que para barras (horizontais) vamos ordenar de forma decrescente (maior em cima) e de colunas (verticais) em ordem crescente (maior à direita).

Sobre a atualização dos dados, nossa expectativa é não alterar mais nenhum deles. Mas pode ser que um ou outro precise de um ajuste pontual. Mas fica a seu critério o que acha melhor (eu realmente espero não alterar mais esses dados).

**Comment by andresmrm** [comment]
Estava vendo aqui, será que não precisa ver caso a caso?
Por exemplo, no perfil populacional, o de faixa etárias é melhor que esteja organizado da menor faixa etária para a maior, não? Ainda na mesma página, o que fala de raça/cor, tem um "outras" que acho que deveria ser a última barra, não?

**Comment by andresmrm** [comment]
Em Trabalho e Educação também tem o de escolaridade, que tem uma ordem própria.
Depois tem os que são masculino e feminino... (ordenar por qual barra?)

O que daria para seguir essa política que vocês colocaram são os de UFs. (são todos barras horizontais, e ficariam do maior para menor)

**Comment by andresmrm** [comment]
Ordenei os gráficos de UFs.

**Comment by diraol** [comment]
Acho que faz sentido o que você disse andres, e acho que a proposta era mais focada mesmo em 'regra geral' e que vão ter outros cases mesmo
