### ISSUE TITLE
Login/cadastro de usuários [backend]

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#121]
O cadastro dos usuários na plataforma não está funcionando.

Existe um problema de usabilidade do formulário (no modal) de cadastro. Mas, para além disso, no ambiente de produção o formulário não está funcionando (e eu não consegui descobrir o motivo ainda).

Pensei em duas alternativas. Uma delas seria resolver esse problema e outra seria realizarmos a autenticação dos usuários (não administrativos) via SocialLogin/OAuth (Google/Facebook).

Lembrando que este login serve, basicamente, para permitir o acesso aos contatos dos especialistas.

Caso o cadastro seja realizados só internamente em nossa plataforma, não é nosso intuito que os cadastros precisem ser aprovados, mas idealmente os usuários precisariam receber um email para poder validar o email e o cadastro antes de poderem acessar os dados que demandam cadastro.
Além disso, outro ponto que precisa ser melhorado para além da estética, é que as labels dos "campos" estão em inglês (e algumas labels sequer estão sendo mostradas, como `username` no cadastro).

A feature de "recuperar password" também está com problemas....

**Comment by hsvab** [comment]
Um erro de preenchimento envia para essa página:

![image](https://user-images.githubusercontent.com/2137923/42414375-7e18e530-820a-11e8-9090-f34723c207b7.png)

Aí, não tem como mandar os dados e o link de novo cadastro no modal e ao fazer login para de funcionar.

**Comment by hsvab** [comment]
Se houver necessidade de confirmação ou ativação de cadastro (pela Conectas e automática no email do usuário) é preciso ter mensagem avisando isso para alinhar a expectativa do usuário de como funciona esse cadastro, algo como "você receberá um email quando sua conta ficar ativa".

**Comment by andresmrm** [comment]
Uma coisa para pensar aqui é sobre como colocar os botões de usuários (login, logout, edição de dados etc), como estilizar. O Mezzanine já vem com algo padrão que coloquei aqui para testarmos:
https://github.com/ask-ar/carceropolis/blob/0e2b3d30c4ee0daefd0d30573bb8d14423f43be8/carceropolis/carceropolis/templates/base.html#L57

**Comment by andresmrm** [comment]
Só para confirmar, é o @diraol que está tocando essa issue, né?

**Comment by diraol** [comment]
Oi Andres, estou vendo isso sim!!!! :)
