### ISSUE TITLE
Login/Cadastro de usuários [frontend]

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#122]
Precisamos melhorar esteticamente os forms relacionados aos modais de login/cadastro [ver exemplo ao clicar em "Faça login para ver os contatos": http://carceropolis.org.br/especialistas/].
- [x] Trocar labels do cadastro (para português)
- [x] Campo de username está sem label e fica parecendo que é para repetir o email
- [ ] melhorar layout no geral
- [x] Corrigir o ícone de "login/cadastro" na barra superior.

**Comment by hsvab** [comment]
- [x] Trocar labels do cadastro (para português)
- [x] Campo de username está sem label e fica parecendo que é para repetir o email
- [ ] melhorar layout no geral

![image](https://user-images.githubusercontent.com/2137923/42414346-1a50859e-820a-11e8-9e51-d55ca3232066.png)

**Comment by andresmrm** [comment]
Vou tentar tocar essa.

**Comment by andresmrm** [comment]
Pelo que eu vi aqui rodando a master já fizeram, não? Já está em português e está mais bonitinho.

**Comment by diraol** [comment]
Acho que sim, não sei se tem algo mais que deveria ser feito.
@hsvab você pode validar, por favor?

**Comment by vanessametonini** [comment]
é pelo que to vendo, alguém já arrumou
![screen shot 2018-07-24 at 11 58 25](https://user-images.githubusercontent.com/3089882/43147237-f2ca5964-8f38-11e8-8d85-1d0232eb2b6c.png)

**Comment by vanessametonini** [comment]
Dá pra melhorar um pouco, por exemplo o botão ta sem estilos. Encontrei outros bugs tbm:
**ícone menu:**
![screen shot 2018-07-24 at 11 59 22](https://user-images.githubusercontent.com/3089882/43147302-1aa653a2-8f39-11e8-9395-492d282e66cc.png)

**botoes gigantes em login e cadastro:**
![screen shot 2018-07-24 at 11 58 07](https://user-images.githubusercontent.com/3089882/43147341-31f928b8-8f39-11e8-9c82-fdd5a7e0ba6f.png)

![screen shot 2018-07-24 at 11 58 01](https://user-images.githubusercontent.com/3089882/43147348-38428fd4-8f39-11e8-9ad2-f6010e761eae.png)

**Comment by diraol** [comment]
@vanessametonini adicionei mais um item nessa issue, referente ao ícone do "botão" que fica na barra superior.
