### ISSUE TITLE
[Infográfico] menu lateral direito

### ISSUE THREAD

**Issue by hsvab** [ask-ar/carceropolis#124]
- [x] acertar apra que não fique sobre a infografia

![image](https://user-images.githubusercontent.com/2137923/42414270-16ccd668-8208-11e8-9eb7-2f629228d4a6.png)

- [x] acertar para que não fique sobre o log da ASK (embaixo à direita)

![image](https://user-images.githubusercontent.com/2137923/42414250-b34d3f7e-8207-11e8-891c-6a7210fb0305.png)

**Comment by andresmrm** [comment]
Qual largura de tela estamos considerando como mínima?
Ou se não tem uma largura mínima, a ideia é que as outras coisas se espremam à esquerda do menu?

**Comment by diraol** [comment]
Acho que, nesse caso, tirando eventuais adaptações para mobile (no qual talvez esse menu lateral suma), acho que a ideia é garantir uma margem à direita de forma que o menu não sobreponha a infografia. Está funcionando para a maioria dos "blocos", mas alguns tem pequenas diferenças.

Estou anexando os três primeiros "blocos" para mostrar o problema. Todos os screenshots foram tirados com a mesma resolução

![ss_perfil](https://user-images.githubusercontent.com/192702/42978991-4508c12a-8ba6-11e8-9bc2-d89d68250155.png)
![ss_dados_gerais](https://user-images.githubusercontent.com/192702/42978992-452d96bc-8ba6-11e8-99ad-ddcdc3bddb26.png)
![ss_infra](https://user-images.githubusercontent.com/192702/42978990-44e6005e-8ba6-11e8-8662-9df8d5a3fe6d.png)

**Comment by andresmrm** [comment]
Não sei se entendi, nessas imagens não tem problemas, os problemas estão em
outros blocos, é isso?
Porque aí, pelo que vejo, o menu não está sobrepondo nada. Mas nas imagens que
a Haydee colocou sim.

Vocês estão trabalhando com uma resolução mínima?
Porque em resoluções de mobile, pelo que eu vejo aqui, teria que dar uma
reestruturada boa para ficar legível.

Se deitar o celular talvez ajude, mas dai o menu não cabe mais (teria que ter
um scroll para ele? talvez ficasse estranho...).

**Comment by diraol** [comment]
Vamos lá.
Não sei dizer qual foi a resolução que a @hsvab utilizou para fazer aqueles prints.

No meu caso, era uma área grande o suficiente para caber o infográfico, o menu lateral, e ficar uma pequena sobra. Meu objetivo foi mostrar que a "distância do menu lateral para a borda do infográfico não estava constante (ou seja, nem todos os "blocos" estão do mesmo tamanho). Acho que esse é o primeiro ponto a ser corrigido.

No caso do print da Haydée, eu *acho* que ela estava com a janela num tamanho que não cabe o bloco + menu ao mesmo tempo. Ai, neste caso, eu acho que entraria nos "refactorings/ajustes" para mobile.

No caso de mobile acho que precisamos pensar em outra solução (talvez um menu horizontal fixo no rodapé? Não sei se cabe, mas acho que tem que ser uma solução trabalhada em separado).

**Comment by vanessametonini** [comment]
Acho que pra mobile pode ser apenas uma "aba" q vc clica e mostra ou esconde este menu

**Comment by hsvab** [comment]
Pode ser sim - vc implementa?

Em sex, 17 de ago de 2018 19:52, Vanessa Me Tonini <notifications@github.com>
escreveu:

**Comment by vanessametonini** [comment]
@hsvab fiz o menuzinho que recolhe e abre com a aba. a aba vai estar sempre escondendo o menu para telas menores de 1320px de largura.
