### ISSUE TITLE
[Infografico] Animação - infraestrutura

### ISSUE THREAD

**Issue by hsvab** [ask-ar/carceropolis#125]
Na primeira vez que passa, a sequência funciona. Mas não é possível voltar e se a pessoa clica mais de uma vez na setinha, trava.
![image](https://user-images.githubusercontent.com/2137923/42414289-5feec3a6-8208-11e8-96fa-2a4144ba94a0.png)

- [x] colocar flechinha de avanço e de retorno na animação
- [x] consertar bug quando clica mais de uma vez

**Comment by vanessametonini** [comment]
@hsvab , acho que nao precisamos de flecha para retorno, pensei que seria mais simples ela ficar em loop, quando chega em 48, volta pra 10. O que acha?

**Comment by diraol** [comment]
@vanessametonini o problema de fazer o loop de forma automática é que se a pessoa demorar um pouco mais para ler ela perde completamente o texto. Sei que pode parecer pouco texto, mas considerando que tem os bonequinhos e tudo mais, vamos cair nos casos de ou ficar muito lento para algumas pessoas ou muito rápido para outras.
Mas achei que a usabilidade já ficou muito melhor com a alteração que você fez!

**Comment by diraol** [comment]
A Vanessa refatorou o código da animação e ficou muito melhor agora.
Precisamos pedir para o pessoal da Conectas validar se a animação está funcionando no Safari/IE (mas imagino que sim).
