### ISSUE TITLE
[Infografico] Animação - situação jurídica

### ISSUE THREAD

**Issue by hsvab** [ask-ar/carceropolis#126]
Checar quando dispara a animação - às vezes só funciona depois que passa pela seção e volta.

**Comment by andresmrm** [comment]
O que anima no jurídico, as porcentagens (40 e 37)? Aqui no Firefox e Chromium parece funcionar normal.

**Comment by diraol** [comment]
Sim @andresmrm, isso mesmo.

**Comment by vanessametonini** [comment]
@andresmrm é a função `contador` no arquivo `main.js` disparada pelo evento do `scrollspy` (componente do Bootstrap) que emite um evento qdo estamos ativo em alguma seção. Tbm fiz uma verificação de quando a url tiver um hash da seção ativa, no caso `#situacao-juridica`, para disparar a animação dela.

**Comment by vanessametonini** [comment]
@hsvab não consegui reproduzir. Talvez seria no IE? 
Precisamos testar no IE....

**Comment by hsvab** [comment]
Precisa testar no IE e no Safari.

Em ter, 24 de jul de 2018 11:52, Vanessa Me Tonini <notifications@github.com>
escreveu:

**Comment by diraol** [comment]
A Vanessa refatorou o código da animação e ficou muito melhor agora.
Precisamos pedir para o pessoal da Conectas validar se a animação está funcionando no Safari/IE (mas imagino que sim).
