### ISSUE TITLE
[Banco de especialistas] Autocompletar no campo de busca

### ISSUE THREAD

**Issue by hsvab** [ask-ar/carceropolis#127]
Implementar a função de autocompletar nos campos:
- [ ] nome
- [ ] especialidade

**Comment by andresmrm** [comment]
Alguma sugestão do que usar?
Dando uma busca a primeira coisa que me apareceu foi essa:
https://goodies.pixabay.com/javascript/auto-complete/demo.html
Daria para implementar via VueJS se preferirem também. Mas deve ser mais fácil ir com uma lib como a de cima.

**Comment by hsvab** [comment]
Vai de lib então ;-)

**Comment by andresmrm** [comment]
A lib que eu linkei parece que é mais para quando vai pegar os dados via AJAX, que não é nosso caso.
Procurando uma alternativa achei essa:
https://github.com/varvet/tiny-autocomplete
Além dela descobri que há uma funcionalidade padrão no HTML5 para isso:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
Ela não funciona no Safari, mas há polyfill:
https://github.com/mfranzke/datalist-polyfill

Implementei usando Datalist por enquanto porque era o jeito mais fácil. E porque as coisas básicas que precisava implementar para o Datalist funcionar são úteis para qualquer método que formos usar.

Uma particularidade que vi com o Datalist (no FF pelo menos) é que ele pode mostrar outras strings que a pessoa tenha escrito em inputs com o mesmo nome.

Não coloquei o polyfill por enquanto, para ver se vamos manter o Datalist mesmo ou fazer via JS.

**Comment by diraol** [comment]
@andresmrm eu sempre gosto de padrões e recursos "built-in"!
Acho que vale tentarmos o Datalist mesmo e, caso tenhamos problemas que o polyfill não resolva com alguma plataforma específica (Safari ou algum browser versão mobile) ai buscamos outras alternativas. =)

**Comment by diraol** [comment]
(Btw, ficou ótimo!)

De noite avalio com a @hsvab se vale estilizar a janela que aparece do autocomplete. =)

**Comment by andresmrm** [comment]
Sim, eu também prefiro usar os recursos padrões. Mas esse é bem simples.
Se precisar estilizar acho que já teria que fazer tudo via JS.
