### ISSUE TITLE
Responsividade

### ISSUE THREAD

**Issue by hsvab** [ask-ar/carceropolis#132]
Deixar a plataforma o mais mobile-reponsive possível.

**Comment by andresmrm** [comment]
Eu dei uma olhada geral, acho que a parte com problemas é a de dados. Tanto os infográficos como os gráficos. Mas nenhuma das duas me parece muito fácil de resolver...
Você tem alguma coisa mais específica em mente, @hsvab ?
O resto do site me pareceu ok, mesmo em telas bem pequenas.

**Comment by vanessametonini** [comment]
Sim @andresmrm,como o infográfico não foi uma tela pensada em mobile, desde o design até o front, e como precisávamos terminar logo, acabei fazendo seguindo o layout.
