### ISSUE TITLE
Habilitar "drag" do mapa

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#133]
O recurso de arrastar (drag) do mapa não está funcionando quando se clica no mapa, apenas quando se clica nos marcadores das unidades.

**Comment by andresmrm** [comment]
Parece que o problema é causado por essa linha no CSS:
https://github.com/ask-ar/carceropolis/blob/bokeh_dashboard_map_charts/carceropolis/carceropolis/scss/_unidades.scss#L466
@vanessametonini , podemos tirar essa linha, ou gerará problemas no mobile?

**Comment by vanessametonini** [comment]
Podemos tirar sim! Acho que coloquei pq no mobile fica meio confuso, só que faz mais sentido ter isso mesmo. Vou fazer!

**Comment by andresmrm** [comment]
Eita, só vi seu commit agora, ignorem o meu.

**Comment by diraol** [comment]
Gente, vocês tem certeza de que o Drag do mapa está funcionando direitinho?
Testei aqui e só funcionou quando o Drag acontece sobre um dos clusters e/ou pins...

**Comment by andresmrm** [comment]
Fui testar agora e meu mapa está vazio. =(
De qualquer jeito, estou conseguindo arrasta-lo com o mouse.

Tem ideia de porque não há unidades no mapa? Tentei rodar via docker mas não adiantou.

**Comment by diraol** [comment]
Você carregou os dados? (Loaddata)?

**Comment by andresmrm** [comment]
[2018-07-21 19:50] Diego Rabatone Oliveira:
> Você carregou os dados? (Loaddata)?

Agora foi, vlw!
Achei que via Docker não precisava fazer isso.

Até agora eu não estava usando Docker, mas acho que mudou algo no
"initialdata.json.bz2", pois o SQLite não estava conseguindo importar.
Fiquei com preguiça de configurar o PostgreSQL e estou tentando usar o Docker
(e também porque estava tendo que fazer um malabarismo com git stash e umas
configurações próprias no settings.py para poder rodar sem Docker).

Bom, o drag do mapa está funcionando bem para mim. No Firefox e Chromium.

**Comment by diraol** [comment]
Em teoria, via docker quando você sobe os containers pela primeira vez ele deveria carregar os dados sim (teve um commit meu há um tempo que desabilitou isso, mas isso já foi readicionado no código que está na branch "master" [https://github.com/ask-ar/carceropolis/blob/master/deploy/entrypoint.sh].

Sobre o SQLite, talvez seja o tamanho do arquivo, que aumentou MUITO (eu subi o dataset full do infopen). Inclusive o próprio carregamento lá no servidor de produção foi difícil, faltou memória RAM no server para carregar os dados na base, tive que fazer uma "gambiarra" com swapfile para conseguir....

Sobre settings/docker, se o problema que você estava tendo é só com o arquivo do settings, podemos achar uma alternativa. Podemos fazer o settings verificar se existe um arquivo "local_settings.py" e, caso exista, ele carrega (e sobrescreve o que tiver lá). Te ajuda?

Sobre o Drag do mapa, vou rodar de novo assim que chegar em casa! =) Valeu!

**Comment by diraol** [comment]
Working! Valeu!
