### ISSUE TITLE
Erro ao impotar fixture das cidades

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#138]
Zerei o BD aqui e estou tentando reimportar tudo, mas esse comando está dando erro:

    $ python manage.py loaddata cidades/fixtures/cidade.json.bz2
    CommandError: No fixture named 'cidade' found.

O `carceropolis/fixtures/initialdata.json.bz2` foi.

**Comment by diraol** [comment]
@andresmrm .... `cidades.json.bz2`, e não `cidade.json.bz2`

**Comment by andresmrm** [comment]
=D Vlw!
Vou corrigir na documentação.
