### ISSUE TITLE
Busca para publicações

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#16]
Desenvolver busca simples de conteúdos publicados, por palavra chave;

**Comment by hsvab** [comment]
Está pronto? Podemos fechar esta issue?

**Comment by diraol** [comment]
Fiz a parte do backend e implementei um form "cru" na página (Dentro de uma determinada categoria das publicações).

Passando a bola para a @vanessametonini =)

[Pensei em fazer uma barra que "some e aparece" conforme o usuário clica num botão de lupa no canto direito...]
