### ISSUE TITLE
Página Abertura

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#28]
- [x] Vídeo de fundo
- [x] Logo centralizada
- [x] Texto de abertura
- [x] Botões para páginas Dados e Publicações
- [x] Esconder Footer

**Comment by vanessametonini** [comment]
Falta:
vídeo oficial
substitui por logo oficial (laranja e vermelha)
texto oficial
esconder footer

**Comment by vanessametonini** [comment]
Ainda faltam informações oficiais (vídeo, texto)

**Comment by hsvab** [comment]
E também falta envio da imagem (para uma abertura estática) para a Home
