### ISSUE TITLE
Página Dados

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#29]
- [x] Submenu com ícones
- [x] Breadcrumb
- [ ] Lista de Gráficos
- [ ] Lista esquerda
- [ ] Item destacado
- [ ] Lista direita
- [ ] _Mobile Friendly_

**Comment by diraol** [comment]
As páginas de dados serão planejadas por uma pessoa da área de design a ser contratada.
Fechando a issue.
