### ISSUE TITLE
Filtro de dados parte 01: Menu de filtros

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#30]
- [ ] Mapa
- [ ] Filtros
- [ ] Texto

![screen shot 2016-09-01 at 23 42 21](https://cloud.githubusercontent.com/assets/3089882/18191067/d60c2afc-709d-11e6-9853-6aacc110c54b.png)

**Comment by hsvab** [comment]
Sugestões resultantes da reunião de 20/09/16:
i) que o ícone tenha um texto associado, por exemplo: MAPAS, FILTROS, BUSCA
ii) que a localização desses menus seja abaixo dos ícone de seleção mais macros

**Comment by diraol** [comment]
As páginas de dados serão planejadas por uma pessoa da área de design a ser contratada.
Fechando a issue.
