### ISSUE TITLE
Filtro de dados parte 02: visualizar dados por (limite região)

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#31]
- [ ] Abas: Todos Brasil x Por Estado
- [ ] Mapa de seleção do Estado
- [ ] Zoom do Mapa

![screen shot 2016-09-01 at 23 50 28](https://cloud.githubusercontent.com/assets/3089882/18191209/e48648a0-709e-11e6-84ed-74c4cd6c37d2.png)

**Comment by diraol** [comment]
As páginas de dados serão planejadas por uma pessoa da área de design a ser contratada.
Fechando a issue.
