### ISSUE TITLE
Filtro de dados parte 03: período / gênero / regime

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#32]
- [ ] Por Período
- [ ] Por Gênero
- [ ] Por Regime
- [ ] Limpar filtros

![screen shot 2016-09-01 at 23 52 30](https://cloud.githubusercontent.com/assets/3089882/18191246/35cb3bf8-709f-11e6-85ee-4883b42164ac.png)

**Comment by diraol** [comment]
As páginas de dados serão planejadas por uma pessoa da área de design a ser contratada.
Fechando a issue.
