### ISSUE TITLE
Filtro de dados parte 04: filtro por texto

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#33]
- [] Input de texto
- [] Lista de resultados (?)

![screen shot 2016-09-01 at 23 54 29](https://cloud.githubusercontent.com/assets/3089882/18191264/75ce1856-709f-11e6-9283-2032b0068a18.png)

**Comment by diraol** [comment]
As páginas de dados serão planejadas por uma pessoa da área de design a ser contratada.
Fechando a issue.
