### ISSUE TITLE
Compartilhar redes sociais

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#34]
- [ ] Compartilhar desktop
- [ ] Compartilhar mobile / nativo OS

**Comment by hsvab** [comment]
Precisamos que Conectas nos envie a lista de redes sociais para avançar com esta issue?

**Comment by hsvab** [comment]
É interessante poder compartilhar também um gráfico específico ou mesmo o infográfico.

**Comment by hsvab** [comment]
Ícone de Face (https://www.facebook.com/conectas/) e Instagram (https://www.instagram.com/_conectas/) em algum lugar (talvez rodapé)?

**Comment by andresmrm** [comment]
Quais redes estão pensando aqui? Facebook? Whatsapp? Twitter?
Seria simplesmente colocar botões que compartilhem o link atual?

> É interessante poder compartilhar também um gráfico específico ou mesmo o infográfico.

Mas dai colocaria botões de compartilhamento em cada infográfico ou gráfico? Não vai ficar muito carregado? Talvez um botão compartilhar que abra uma janela com opções de compartilhamento?

**Comment by diraol** [comment]
> Quais redes estão pensando aqui? Facebook? Whatsapp? Twitter?
Pensando alto: Facebook, Whatsapp, Twitter

> Seria simplesmente colocar botões que compartilhem o link atual?
Tendo a achar que sim.

> Mas dai colocaria botões de compartilhamento em cada infográfico ou gráfico? Não vai ficar muito carregado? Talvez um botão compartilhar que abra uma janela com opções de compartilhamento?

De fato talvez seja meio "poluído" ter botão de compartilhar em cada gráfico numa mesma página.
O que você quis dizer com "opções de compartilhamento"?

Será que não tem nenhuma ferramenta meio padrão (será que precisa?)

**Comment by andresmrm** [comment]
[2018-07-19 22:55] Diego Rabatone Oliveira:
> O que você quis dizer com "opções de compartilhamento"?

Aqueles botões que abrem uma lista com várias redes para você escolher em qual
compartilhar.

> Será que não tem nenhuma ferramenta meio padrão (será que precisa?)

Deve ter JSs para isso por aí sim.
Mas se formos fazer algo mais simples, só umas 3 redes, e aparecer em só um
lugar da página, também acho que não precisa.

**Comment by diraol** [comment]
> Aqueles botões que abrem uma lista com várias redes para você escolher em qual compartilhar.

Ah, entendi! Boa!

> Deve ter JSs para isso por aí sim.
> Mas se formos fazer algo mais simples, só umas 3 redes, e aparecer em só um lugar da página, também acho que não precisa.

Justo.

Acho que podemos/devemos ter:
 - Facebook
 - Twitter
 - ?
@hsvab mais sugestões?

**Comment by hsvab** [comment]
Facebook, Twitter, Instagram e WhastApp

**Comment by vanessametonini** [comment]
Na época que criamos essa issue o compartilhar era das publicações se não me engano. O @andresmrm vai colocar nos gráficos pelo que entendi. Onde mais precisamos colocar? 
O fale conosco tá meio vazio, a coluna da direita. Podemos colocar os links das redes da conectas lá tbm, o que acham?

**Comment by andresmrm** [comment]
O que eu tinha comentado era algo como esse:
https://www.cssscript.com/demo/create-social-share-popup-box-with-pure-javascript-needsharebutton
Achei que teria algo biblioteca mais consolida para isso, mas não achei...

Como ficamos com essa issue?
Usamos um menu desse tipo? Ou colocamos os botões de cada rede direto na
página?
Também refaço as perguntas que a Vanessa fez.
