### ISSUE TITLE
Publicações: post

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#37]
- [x] ~~Imagem destaque~~ (não vamos ter um campo para isso)
- [x] Título
- [x] Autor/ Data
- [x] Estilo de texto (parágrafo, negrito, italico, link, listas)
- [ ] Compartilhar
- [x] _Mobile friendly_

**Comment by vanessametonini** [comment]
@diraol fazer o template do detalhe do post

**Comment by diraol** [comment]
Na versão "mobile" não tem breadcrumb (havíamos optado por isso), mas navegando agora, fazendo um teste, me pareceu que ficou ruim sem alguma espécie de breadcrumb ou de botão voltar, visto que não há indicação de "aonde se estava antes" (qual página de publicações). Acho que um botão voltar cairia bem.... Talvez na barra superior?
