### ISSUE TITLE
Página de Especialistas

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#38]
- [x] Lista de especialistas
- [x] _Mobile Friendly_

**Comment by hsvab** [comment]
Estrutura de Dados do Cadastro de especialistas fechado na reunião de 20/09/0216.

**Comment by vanessametonini** [comment]
@diraol 
Fazer a lista do front por área de atuação, e verificar/listar as especialidades por especilistas

**Comment by vanessametonini** [comment]
Vou abrir uma issue nova para a barra de busca

**Comment by hsvab** [comment]
O estilo de Especialistas está diferente de Publicações (espaçamento entre as caixas, arredondamento, fontes e cores). É interessante uniformizar Especialistas e Publicações p/ que tenham a mesma linguagem.

**Comment by diraol** [comment]
Será que faz sentido colocar a mesma "tela inicial" que temos na parte de
publicações com as "grande áreas"?

**Comment by hsvab** [comment]
@diraol podemos ver isso com a Conectas na próxima reunião...

**Comment by hsvab** [comment]
Em reunião de 09/ago/2017 com Conectas foi decidido que:

- [x] não haverá a separação das sessões nos subttítulo, embora os especialista continuarão a ser agregadaos nas 5 macro-áreas
- [x]  deverá haver 3 campos de busca:
    - [x]  macro áreas onde será possível selecionar de uma lista
    - [x]  especialidade, que fará a busca no campo especialidade (tags)
    - [x]  nome do especialista, que fará a busca no campo nome do especialista
- [x] pode-se ordenar os especialistas por odem alfabética
- [x] mostrar até 12 por página.

@vanessametonini para quando acha que consegue fazer essas alterações?
