### ISSUE TITLE
Ajuste de configurações de Email do Projeto

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#42]
Acertar as configurações do backend para envio de emails.

Precisamos definir como será este envio de email, se há algum tipo de servidor de email (com email da conectas/carceropolis) que podemos utilizar e que tem autenticação, para evitar cair em caixa de spam.

**Comment by hsvab** [comment]
Podemos discutir isso até /na próxima reunião com a Conectas?

**Comment by diraol** [comment]
http://www.rosslaird.com/blog/customizing-mezzanine/

**Comment by diraol** [comment]
Este recurso está funcionando, porém ainda com um "email fake" (um email temporário que eu criei para testarmos o recurso em si).

Precisamos de um "email oficial" do projeto que possa ser utilizado, ou algum da conectas.
É preciso ser um email com suporte a SMTP.
Precisamos das seguintes informações:

1. *EMAIL_HOST_USER*: username ou email completo
2. *EMAIL_HOST*: algo como `smtp.gmail.com`
3. *EMAIL_HOST_PASSWORD*: ....
4. *EMAIL_PORT*: Geralmente é a 587, mas alguns serviços de email utilizam outras portas
