### ISSUE TITLE
Barra de busca para especialistas

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#45]
Fazer barra de busca por texto na página de especialistas

**Comment by hsvab** [comment]
Acho bom deixar a busca na página de especialistas parecida com Publicações. Por exemplo, indicados box paraos seguintes filtros: 
1) Nome do(a) especialista
2) especialidades
3) macro-área (funcionamento do sistema | Perfil Populacional | Política Criminal | Sistemas Internacionais | Violência Criminal)
