### ISSUE TITLE
Fazer modal para autenticação na página de especialistas

### ISSUE THREAD

**Issue by vanessametonini** [ask-ar/carceropolis#47]
Neste modal, a pessoa pode escolher entre logar ou criar cadastro.

Após o login, ela já estará a ver as infos de email e telefone dos especialistas.

**Comment by hsvab** [comment]
@diraol é possível mudar de "username" para "nome de usuário ou email" e de "password" para "senha"?

**Comment by hsvab** [comment]
@vanessametonini confere se o estilo está de acordo com a nova identidade visual?
Além disso, o botão está 'grudado' no campo de preenchimento da senha.
