### ISSUE TITLE
Implementar suporte a multiplos idiomas

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#50]
Válido para conteúdos estáticos (blocos de texto fixos, páginas "estáticas" e campos de formulários.

**Comment by diraol** [comment]
Django internationalization:

http://stackoverflow.com/questions/38162929/django-how-to-allow-translation-from-admin-and-guest-language-picker

http://stackoverflow.com/questions/10280881/django-site-with-2-languages

**Comment by andresmrm** [comment]
A documentação do Mezzanine tem uma própria página sobre Multi-Lingual:
http://mezzanine.jupo.org/docs/multi-lingual-sites.html
Vou tentar seguir por aí. Mas não tenho certeza se será o bastante.

**Comment by andresmrm** [comment]
Parece que deu certo. Ele já tem um seletor de idioma próprio. Perguntas:
- Onde colocar o seletor de idioma e qual cara terá?
- Parece que ele está salvando o idioma em algum cookie/sessão. Está bom o bastante ou teria que ter URLs próprios para cada idioma? (algo como carceropolis.org.br/en/artigo-legal)
- Eu vi que você setou alguns nomes de atributos da classe `Publicacao` na mão, sendo que vários já estão definidos em BlogPost (do qual ela herda). Isso é só por questão de tradução? Se sim, talvez não precise setar na mão, só configurar a tradução corretamente (acho).

**Comment by andresmrm** [comment]
Dei um push caso queiram ver como está.

**Comment by diraol** [comment]
Oi @andresmrm, vi a alteração que você fez (no source), mas não vi nenhum impacto dela na plataforma. Nem na área de admin nem na de frontend.

Com relação à alteração que você fez par adicionar o seletor no front, dá uma olhada na branch master que eu fiz uma alteraçãozinha para que ele fique na barra já existente (depois podemos melhorar ainda mais).

**Comment by andresmrm** [comment]
[2018-07-14 17:08] Diego Rabatone Oliveira:
> Oi [1]@andresmrm, vi a alteração que você fez (no source), mas não vi nenhum
> impacto dela na plataforma. Nem na área de admin nem na de frontend.

Estranho, porque aqui ele alterou. No frontend apareceu o botão seletor de
idiomas. No admin, na edição de artigos, apareceu um botão pt/en para escrever
as duas versões para um mesmo artigo.

> Com relação à alteração que você fez par adicionar o seletor no front, dá uma
> olhada na branch master que eu fiz uma alteraçãozinha para que ele fique na
> barra já existente (depois podemos melhorar ainda mais).

Ok, vou ver.

**Comment by hsvab** [comment]
@andresmrm consta como entregável o seguinte: "(ii) suporte a inglês e português nas páginas home, fale conosco, sobre nós, publicações (somente títulos de seções) e banco de especialistas (somente títulos de seções)"

**Comment by andresmrm** [comment]
> publicações (somente títulos de seções)

Esse já é para estar funcionando.

> e banco de especialistas (somente títulos de seções)

Quais são os títulos de seções? Macro áreas/Áreas de Atuação? Ou especialidades?

**Comment by andresmrm** [comment]
Acho que já sei qual é o problema. Eu não gerei as migrations.

**Comment by andresmrm** [comment]
As migrations deram mais trabalho do que eu esperava, e ficou meio estranho, mas foi o que entendi que é para fazer e que funcionou.
Commit: https://github.com/ask-ar/carceropolis/commit/dfc7c270bd3d0a2fc1af1b03920cd597ded0362c
Doc do Mezzanine sobre: http://mezzanine.jupo.org/docs/multi-lingual-sites.html#translation-fields-and-migrations

O primeiro método que ele sugere me pareceu bem ruim e manual. Não testei. Segui o segundo.
O problema todo é que ele modifica a estrutura dos models de sub apps do Mezzanine (pages, blog, forms e conf) para comportar campos para as traduções.
Dai quando gera as migrations ele estava criando migrations para esses apps em /site-packages/...
Quem contorna isso é o MIGRATION_MODULES. Tentei de vários jeitos e o que funcionou foi copiar todas as migrations desses módulos para uma pasta nossa. Ou seja, uma espécie de fork nelas:
https://github.com/ask-ar/carceropolis/tree/dfc7c270bd3d0a2fc1af1b03920cd597ded0362c/carceropolis/carceropolis/migrations

Para rodar esse código novo, além de executar as migrations, é preciso instalar um pacote novo que coloquei no requirements.

**Comment by andresmrm** [comment]
@diraol você tinha comentado algo sobre dar rebase nas nossas branches, é para fazer isso com essa? Ou era só para as branches velhas naquele momento que você falou?

**Comment by andresmrm** [comment]
Na home, como tem coisas escritas direito no HTML, adicionei novas "traslation messages".
Caso precise mexer nisso, primeiro adiciona o que quer traduzir com `{% trans "palavra ou id" %}`, depois gera os `.po`:

    python manage.py makemessages -l en -l pt_BR

Depois edita:

    carceropolis/carceropolis/locale/en/LC_MESSAGES/django.po
    carceropolis/carceropolis/locale/pt_BR/LC_MESSAGES/django.po

E por fim compila:

    python manage.py compilemessages

Mais informações aqui: https://docs.djangoproject.com/en/2.0/topics/i18n/translation/

Os botões da barra de menu superior podem ser modificados traduzindo o título das páginas pela própria interface de admin.

**Comment by andresmrm** [comment]
**Acho** que agora foi tudo. Vejam se funciona aí e se falta algo.

**Comment by diraol** [comment]
Cara, ficou ótimo!!!!

Só ficou um "texto home-intro" na home que ficou estranho...

Sobre o "rebase", acho que vale sempre, principalmente para não termos problemas de "sobreposição" de alterações. =)
Eu tenho o hábito, em quase todos os projetos que me envolvo, a sempre fazer rebase para ter a versão mais nova de todo o código.

**Comment by andresmrm** [comment]
[2018-07-16 11:04] Diego Rabatone Oliveira:

> Cara, ficou ótimo!!!!
> 
> Só ficou um "texto home-intro" na home que ficou estranho...

Sério? No navegador? {% trans "text-home-intro" %} isso deveria ser
traduzido aparecendo o texto em si. Aqui está funcionando.
Será que é porque aí não tem o compilado das traduções? (.mo)
Comito eles ou você gera aí?

> Sobre o "rebase", acho que vale sempre, principalmente para não termos
> problemas de "sobreposição" de alterações. =)
> Eu tenho o hábito, em quase todos os projetos que me envolvo, a sempre fazer
> rebase para ter a versão mais nova de todo o código.

Rebased. Eu só fico meio assim as vezes de dar rebase porque ele implica em
dar um push forçado, né?

**Comment by diraol** [comment]
> Aqui está funcionando. Será que é porque aí não tem o compilado das traduções? (.mo) Comito eles ou você gera aí?
Se puder comitar eu agradeço!

> Rebased. Eu só fico meio assim as vezes de dar rebase porque ele implica em dar um push forçado, né?
Eu acho que se é numa branch em que você está trabalhando sozinho não tem problema....

Ah, e seria legal colocar instruções de como atualizar a tradução no "CONTRIBUTING"! =)

**Comment by andresmrm** [comment]
Feito. =)

**Comment by diraol** [comment]
Valeu!
Chegando em casa hoje eu vejo ;)

**Comment by diraol** [comment]
> Rebased. Eu só fico meio assim as vezes de dar rebase porque ele implica em dar um push forçado, né?

Só pra não perder o comentário, eu pessoalmente não vejo problema se isso for feito numa branch específica na qual você está desenvolvendo "sozinho" e é relativa a uma feature específica.

Em especial logo antes de um "Merge Request", o que evita conflitos na hora de fazer o merge.

Além disso, ele (rebase) garante que você está trabalhando com o código mais atual tbm, o que eu acho sempre positivo.
