### ISSUE TITLE
Definir entre Bokeh e Dash

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#52]
Para implementar um Dashboard, precisamos definir se utilizaremos [Bokeh](http://bokeh.pydata.org) ou [Dash](https://plot.ly/products/dash/).

**Comment by andresmrm** [comment]
Dei uma lida nesse artigo que dá uma visão geral do Dash:
https://medium.com/@plotlygraphs/introducing-dash-5ecf7191b503

Tentei procurar sobre Django e Dash e realmente não encontrei nada.
https://community.plot.ly/t/dash-and-django/4587
Para piorar já existe um plugin de criação de dashboards em Django chamado Dash...
Como diz um dos comentários que achei: Dash é um nome terrível, existem
milhares de Dashes...

Quanto a uma comparação entre os dois, achei esse comentário que parece vir de
um dos desenvolvedores do Bokeh:
https://www.reddit.com/r/Python/comments/3t6tzk/plotly_is_now_free_and_opensource/cx4w6ae/
Na visão dele Dash seria mais voltado a múltiplas linguagens, e Bokeh se
concentra mais em Python.


Tendo em vista principalmente a questão da integração com Django, vou começar
a experimentar com Bokeh.

**Comment by andresmrm** [comment]
Pelo que vi na doc do Bokeh, para integrar com Django teria que usar um IOLoop
do Tornado:
http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#embedding-bokeh-server-as-a-library
E o Tornado serviria tanto o Django como o Bokeh.

Parece que ficaria semelhante a esse exemplo em Flask:
https://github.com/bokeh/bokeh/blob/0.12.6/examples/howto/server_embed/flask_embed.py

Parece aceitável?

**Comment by diraol** [comment]
@andresmrm , se eu entendi direito precisamos do Bokeh Server para poder realizar "operações" com os dados no lado "server-side" sem deixar essa responsabilidade para o browser, é isso? Operações = filtros, agregações, etc.
As alternativas seriam mandar todos os dados para o navegador e fazer ele se virar para filtrar/agregar, etc; ou ficar fazendo um monte de requisições "na mão" entre cliente e servidor.
Entendi direito?

Se sim, acho que faz sentido o que você colocou. Só fico na dúvida se faríamos isso via um server Tornado rodando "na paralela" ou se vale usar uma das duas seguintes opções:
1. https://github.com/askprateek/Django-Graph-Plotter
2. https://github.com/django/channels [para fazer o django lidar com websockets]

(peguei o link 1 daqui: https://www.hackerearth.com/practice/notes/bokeh-interactive-visualization-library-use-graph-with-django-template/ )

**Comment by andresmrm** [comment]
> @andresmrm , se eu entendi direito precisamos do Bokeh Server para poder realizar "operações" com os dados no lado "server-side" sem deixar essa responsabilidade para o browser, é isso? Operações = filtros, agregações, etc.

Isso.

> As alternativas seriam mandar todos os dados para o navegador e fazer ele se virar para filtrar/agregar, etc; ou ficar fazendo um monte de requisições "na mão" entre cliente e servidor.
Entendi direito?

Não sei se dá para mandar todos os dados para o navegador usando o Bokeh, de qualquer jeito acho que isso não faz sentido para nós nesse caso.

Uma alternativa parece ser essa:
https://www.hackerearth.com/pt-br/practice/notes/bokeh-interactive-visualization-library-use-graph-with-django-template/
Usar uma view no Django para renderizar o gráfico usando o Bokeh e enviar para o template. Mas acho que assim não dá para fazer sliders e coisas dinâmicas no gráfico... Talvez para o que pensamos em colocar no dashboard até agora não precise mesmo, mas pode nos limitar mais para frente...

A terceira alternativa, que está no exemplo em Flask, parece ser rodar o Django e o server Bokeh juntos via Tornado. Não sei bem as consequências disso, mas entendo que seria um "processo" só e que todas as funcionalidades do Bokeh estariam funcionando normalmente.

**Comment by diraol** [comment]
Go ahead no tornado então! Acho que vamos precisar modificar o fabfile, mas
sussa :)

**Comment by andresmrm** [comment]
Acho que consegui fazer um rascunho de integração Django+Bokeh para o servidor de desenvolvimento. Minha preocupação era não estragar o autoreload do Django, e parece que está funcionando.
https://github.com/ask-ar/carceropolis/commit/f80e071c84872db560a818a8b1fa6c970a380522
(criei uma branch `bokeh`, mas ainda não dei merge com as atualizações que você colou no master)

**Para rodar é dar o `runserver` normalmente e abrir http://localhost:8000/painel_dados/**

Basicamente sobrescrevi o comando `runserver` para ele iniciar o servidor de Bokeh em uma thread antes de seguir o fluxo normal dele rodando o servidor de Django.

A integração foi mas difícil do que eu esperava. Em produção teria que fazer diferente, mas não está muito claro quão bom ficaria. Em produção daria para pegar o componente WSGI do Django (que aí eu não pude pegar e servir, porque se não eu iria impedir o autoreload) e serviria ele junto com o Bokeh usando... Tornado? Gunicorn? Os dois?

Poderíamos tentar rodar tudo via Tornado (sem Gunicorn, mas atrás do NginX), mas não sei se o Django via ficar feliz, já que ele é pensado para ser usado via WSGI.
(deploy de Tornado http://www.tornadoweb.org/en/stable/guide/running.html)

Poderíamos tentar rodar tudo via Tornado, que por sua vez seria rodado via Gunicorn (atrás do NginX). Não sei se ficaria pior ou melhor do que a opção acima... A vantagem talvez seja não ter que mudar muito os scripts de deploy.
https://stackoverflow.com/a/31294119

Essa resposta parece discutir os problemas de misturar Tornado e WSGI num mesmo servidor. Dei uma lida rápida, mas ainda não entendi muito bem.
https://stackoverflow.com/a/22067306

Outra opção ainda talvez seja rodar o Django via Gunicorn (WSGI) e o Bokeh via Tornado (processos independentes) e tentar "colar" os dois via proxy do NginX (semelhante a uma das opções que você tinha pensado para Dash, né?). Do jeito que está funcionando atualmente, parece que o Bokeh já deixa o servidor dele rodando em "localhost:5006/bkapp", então parece viável usar o NginX para encaminhar para cada servidor. Algo como:
https://stackoverflow.com/a/2534784

O que acha até aí? Seguimos com o Bokeh? Se sim, que próximo passo tomar?
- Testamos o deploy com ele antes? Qual abordagem seguir?
- Começo a implementar o dashboard?

Ou testo o Dash?

**Comment by andresmrm** [comment]
Acabei avançando com o Bokeh e fazendo alguns comparações rápidas com o Dash.

Aprimorei o servidor de desenvolvimento do Bokeh para reiniciar junto com o Django, assim só precisa reiniciar a página quando fizer mudanças.

Pelo que eu vi nem o Bokeh nem o Dash recarregam o gráfico na página automaticamente quando o código muda.

O Bokeh só tem dropdown sem autocomplete. Ele até tem um text input com autocomplete, mas está bem ruinzinho e não tem como listar todas as possibilidades clicando na setinha (como no caso do dropdown). O Dash parece que tem tanto dropdown com autocomplete como aquele múltiplo dropdown.

Um ponto possível para comparar os dois é quanto à facilidade de ter URLs únicas para cada gráfico. O Dash parece que já tem alguns recursos para controlar a URL, mas não está claro quão fácil seria atrelar isso a mudanças no gráfico. O Bokeh parece que não tem nada do tipo, então teria que fazer via JS mesmo.
https://plot.ly/dash/urls

Agora que estou entendendo um pouco melhor, o Dash parece que não é só para gráficos, ele tenta ser genérico para desenvolver outros tipos de aplicação. A ideia acho que é permitir desenvolver SPAs de Python, o que é interessante. Ele parece ter vários recursos "modernosos", mas aqui está mais pesado do que o Bokeh. E a documentação parece um tanto escassa.

**Comment by andresmrm** [comment]
Acho que esse é parecido com o que estamos pensando, né?
https://demo.bokehplots.com/apps/crossfilter

**Comment by diraol** [comment]
Opa @andresmrm ainda não consegui ler/responder todos os comentários ainda.

De baixo para cima.
Sim, é parecido! Acho que "faltam" algumas coisas, mas parece-me um começo interessante!!

Sobre os 'reloads' (django, bokeh e dash), isso é mais focado no desenvolvimento né? "Em produção" não faz diferença. É isso?

Sim, o dash é super novo, tanto que o 'multipage' foi adicionado semana passada. Esse pode ser um bom motivo para ficar pelo Bokeh, pois ele certamente é mais estável em termos de recursos/features.

Sobre o dropdown/autocomplete, talvez dê para implementar "na mão" via JS usando alguma lib esperta, fazendo o 'replace' do dropdown default depois dele renderizado.

**Comment by andresmrm** [comment]
Tranquilo, eu escrevi demais. hahaah

> Sobre os 'reloads' (django, bokeh e dash), isso é mais focado no desenvolvimento né? "Em produção" não faz diferença. É isso?

Isso.

> Sobre o dropdown/autocomplete, talvez dê para implementar "na mão" via JS usando alguma lib esperta, fazendo o 'replace' do dropdown default depois dele renderizado.

É, pensei em algo assim mesmo. O pessoal do Bokeh até cita essa:
http://leaverou.github.io/awesomplete/

**Comment by andresmrm** [comment]
Bom, estou seguindo com o Bokeh então.

Como "mapeamos" o desenvolvimento aqui no GitHub? Criamos uma issue para cada uma das funcionalidades, ou criamos uma issue com uma "task list", estilo essa abaixo, e discutimos tudo em uma issue só? Também poderíamos fazer os dois juntos.
- [x] eixos personalizáveis
- [x] múltiplos gráficos
  - [x] barras verticais
  - [x] barras horizontais
  - [x] bolinhas (scatter)
  - [x] linha
- [ ] exportação
  - [x] png
  - [ ] csv
- [ ] filtros
- [ ] urls únicos
- [ ] integrar com BD
- [ ] dropdown com autocomplete
- [ ] personalizar aparência
- [ ] impedir gráficos absurdos?

**Comment by hsvab** [comment]
Acho melhor uma issue para cada uma das funcionalidades.

**Comment by diraol** [comment]
Concordo com a Haydée.

**Comment by andresmrm** [comment]
Feito! Fechando essa issue então. Não sei se era para marcá-las com um label, mas como não tinha, não coloquei. De qualquer jeito elas e somente elas estão designadas para mim, então é fácil de filtrar.
