### ISSUE TITLE
Interface de admin em pt-BR

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#53]
https://github.com/ask-ar/carceropolis/commit/1f3b2d0a6c49892ce87930fe180c99ab43e3bca1
Arrumou para você? Aqui parece que foi.

**Comment by diraol** [comment]
Opa, sucesso! Valeu! =)

Só uma observação. Nós estavamos fazendo merges na branch develop, a master estava super desatualizada... 

Como você comitou direto na master, fiz o merge da develop para a master e removi a develop.

**Comment by andresmrm** [comment]
Ops, sorry. =P
