### ISSUE TITLE
Infográfico página principal - implementação

### ISSUE THREAD

**Issue by hsvab** [ask-ar/carceropolis#57]
- [x] bloco 1 - dados gerais
   - [x] estático
   - [x] animações
   - [x] link para página interna
- [x] bloco 2 - perfil populacional
   - [x] estático
   - [x] animações
   - [x] link para página interna
- [x] bloco 3 - infraestrutura
   - [x] estático
   - [x] animações
   - [x] link para página interna
- [ ] bloco 4 - situacao jurídica
   - [x] estático
   - [ ] animações
   - [x] link para página interna
- [ ] bloco 5 - trabalho e educação
   - [x] estático
   - [ ] animações
   - [x] link para página interna
- [ ] bloco 6 - saúde
   - [x] estático
   - [ ] animações
   - [x] link para página interna
- [x] bloco 7 - materno-infantil
   - [x] estático
   - [x] animações
   - [x] link para página interna
- [ ] bloco 8 - alas exclusivas
   - [x] estático
   - [ ] animações
   - [x] link para página interna
- [x] bloco 9 - mapa das unidades
   - [x] box
   - [x] mapa com ícones de unidades georreferenciados
   - [x] filtro de seleção de unidades

**Comment by vanessametonini** [comment]
Pessoal, eu coloquei o link para páginas internas, porém tem páginas que ainda não existem, por exemplo: http://dev.carceropolis.org.br/dados/perfil_populacional/

O que fazer nestes casos?

**Comment by diraol** [comment]
Oi Van, pode deixar os links já como eles vão ficar, mesmo que estejam
direcionando para páginas que não existem ainda.
Ai conforme nós formos criando-as isso vai se resolvendo. =)

Pelo menos a "página da frente" (home de dados com o infográfico) já vai
estar toda certinha.
