### ISSUE TITLE
Exportação em CSV do painel de dados

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#61]
Aqui é exportação dos dados que estão aparecendo no gráfico atual? @diraol @hsvab 
Não é da base inteira, certo?
Vai ser um CSV com uma linha ou uma coluna.

**Comment by diraol** [comment]
Hum....
Fico pensando se exportamos só o dado do gráfico ou se exportamos os dados referentes a "x" e "y" das unidades prisionais. Seria algo como ~1400 linhas (uma para cada unidade) e 2 colunas ("x" e "y").

Ou será que só exportamos os dados restritos dos dados do gráfico?
@hsvab sugestões?
O que acha @andresmrm ? Estou pensando no que faz mais sentido para nosso usuário...

**Comment by andresmrm** [comment]
Fiquei esperando para ver o que a @hsvab falava. hehe

Para mim acho que seria melhor ter como extrair a base toda (depois eu me viraria), mas talvez eu não seja "nosso usuário".
Pensando do lado oposto, me vem em mente alguém que não sabe ou não quer mexer com planilha, o importante seria o gráfico, e a exportação não seria usada.
Mas dai me pergunto: qual seria o uso intermediário, que quer uma planilha, mas não completa?
