### ISSUE TITLE
URLs únicos para os gráficos do painel de dados

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#64]
Quando a pessoa escolhe outras opções para o gráfico, o url atualiza de acordo. Depois, abrindo aquele url, já abre o mesmo gráfico. Útil para compartilhar.
Estou considerando aqui apenas as opções dos seletores (eixos, tipo e filtro) e não coisas como zoom do gráfico ou se ele foi arrastado etc.

**Comment by andresmrm** [comment]
Querystring ou Hash? Acho que Hash é melhor por não fazer o navegador recarregar nunca. Querystring pode fazer isso em navegadores que não suportam edição de histórico.

Qual a melhor forma de codificar os parâmetros no URL?
- Colocar um JSON diretamente?
`/painel_dados/#[["X-Axis","ano"],["Y-Axis","pop_masc"],["Tipo de Gráfico","linha"],["Filtro","Nenhum"],["Valor","Nenhum"],["Valores",[0.1,0.9]]]`
Fica mais ou menos legível, versátil e prático para colocar os dados, mas é um pouco verboso. Talvez seja necessário fazer escaping.
- Codificar com base64?
`/painel_dados/#W1siWC1BeGlzIiwiYW5vIl0sWyJZLUF4aXMiLCJwb3BfbWFzYyJdLFsiVGlwbyBkZSBHcuFmaWNvIiwibGluaGEiXSxbIkZpbHRybyIsIk5lbmh1bSJdLFsiVmFsb3IiLCJOZW5odW0iXSxbIlZhbG9yZXMiLFswLjEsMC45XV1d`
Fica maior ainda, nada legível, mas garante o escaping.
- Montar a hash na mão?
`/painel_dados/#x-ano/y-pop_masc/tipo-linha`
Bem mais compacto, legível, mas mais trabalhoso de programar.
- Outra?

Algum seria menos seguro do que o outro? Lembrando que alguns desses valores podem acabar vindo diretamente do BD.

**Comment by diraol** [comment]
Fala @andresmrm ! =)
acho que o primeiro ponto é: Acho que a URL precisa ser semântica/legível/humana. Então eu excluiria a opção "base64".

Sobre "recarregar o browser", também é possível alterar a querystring sem refresh, utilizando "[pushState](https://developer.mozilla.org/en-US/docs/Web/API/History_API)". Claro que isso demanda um browser com suporte, mas acho que é bem safe hoje em dia assumirmos isso (basicamente suporte a HTML5).

Apesar de gostar do uso de Hashs, acho que o uso da querystring vai facilitar um pouco a vida:
`/painel_dados?x=ano&y=pop_mas&tipo=linha`

Você consegue ver algum "drawback" nisso?

Sobre segurança, não sei se tem grandes diferenças. Tanto em um caso como no outro você vai ler essas informações com JavaScript no frontend e enviar um "request" para ser processado no backend, certo? Se for isso, em ambos os casos precisaremos/poderemos fazer algum tipo de tratamento do lado do backend para evitar alguma dor de cabeça. Faz sentido?

**Comment by andresmrm** [comment]
Tem razão, o pushState está com mais suporte do que eu lembrava:
http://caniuse.com/#search=pushstate

Acho que podemos seguir por aí sim. Só acho que talvez precise fazer um escaping dependendo do que vier do BD. Talvez dê para ver essa questão de segurança no próprio escaping.

**Comment by diraol** [comment]
De fato! Se precisarmos de algo nesse sentido podemos fazê-lo diretamente
no backend. ;)
​

**Comment by andresmrm** [comment]
Com esse último commit essa issue deve estar minimamente funcionando.
Há a possibilidade de reduzir o tamanho do url tirando:
- parâmetros do filtro quando o filtro estiver desativado
- parâmetros que estão com o valor padrão

Acha que vale a pena fazer isso?

**Comment by diraol** [comment]
Cara, faz o seguinte, fecha essa issue e damos isso por encerrado por agora. E podemos abrir uma nova para "otimizar a URL", mas não focar nela por agora (não acho que seja prioridade por hora).
Faz sentido?

**Comment by andresmrm** [comment]
Ok!
