### ISSUE TITLE
Preparar servidor do Bokeh para rodar em desenvolvimento 

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#69]
Com autoreload dos servidores do Bokeh e Django quando o código muda.

f80e071c84872db560a818a8b1fa6c970a380522
c5f2d1704c09edd462f62f7bbb2f53837c4679a7

**Comment by diraol** [comment]
@andresmrm vc pode referenciar a issue no próprio commit colocando o seguibte no commit:
`ask-ar/carceropolis#<issueNumber>`

Da mesma forma você pode fechar a issue direto pelo commit com `fix ask-ar/carceropolis#<issueNumber>` (ou fixes, close, closes) e por ai vai ;)

**Comment by andresmrm** [comment]
Obrigado pela dica! Na verdade eu já conhecia o "fix", e acho que nem precisa do "ask-ar/carceropolis" se a issue for do mesmo repositório do commit. É que as vezes eu fico com preguiça de ir ver o id da issue no momento do commit. =P E nesse caso a issue foi criada depois do commit. Mas vou tentar seguir isso para os próximos.

**Comment by diraol** [comment]
hahahah beleza! =)

De fato não precisa por ser no mesmo repositório.

Abs!
