### ISSUE TITLE
Desenvolver módulo de especialistas

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#7]
Módulo 'Cadastro de Especialistas', uma listagem pública do cadastro, que contará com os campos:
- nome;
- e-mail;
- telefone;
- mini-bio;
- instituição;
- área de atuação (categorias); e
- especialidades (palavras-chave)

**Comment by diraol** [comment]
H: 6

**Comment by hsvab** [comment]
Dados de email e telefone de especialistas não devem ser campos obrigatórios.
