### ISSUE TITLE
Barras superior e inferior fixas

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#71]
Da forma como o footer e o menu superior estão hoje, às vezes temos alguns problemas de design/layout, como por exemplo em:
http://dev.carceropolis.org.br/publicacoes/transgress%C3%A3o-controle-social-e-religi%C3%A3o-um-estudo-antropol%C3%B3gico-sobre-pr%C3%A1ticas-religiosas-na-penitenci%C3%A1ria-feminina-do-estado-do-rio-grande-do-sul/ 
![2017-08-09-191055_1277x951_scrot](https://user-images.githubusercontent.com/192702/29146230-81a93b0c-7d36-11e7-914b-2c910ba9fdc1.png), no qual o "footer" não fica no final da página (por "falta de altura" da mesma).

Além disso, o "header" com os menus também "some" ao longo da navegação vertical.

Pensamos em tentar deixar ambos fixos para ver se melhora a usabilidade.

Talvez o submenu de "dados" (iconográfico)  também pudesse ficar fixo junto da barra superior.

**Comment by vanessametonini** [comment]
Concordo que o footer que que ficar em baixo da janela sempre. Porém header e footer fixos fica bizarro, até porque no footer não contém uma informação importante o suficiente com o conteudo da atual pagina para ficar sempre em exibição. Podemos fazer um teste...

**Comment by diraol** [comment]
Você tem razão Van, footer fixo é bizarro mesmo, péssima sugestão minha.

**Comment by vanessametonini** [comment]
@diraol fiz no branch front o Header fixo e arrumei o footer pra ficar sempre embaixo da janela. Vejam se ficou bom! :)

**Comment by vanessametonini** [comment]
Vcs acham que precisa de header fxo pra versão mobile também?

**Comment by diraol** [comment]
@vanessametonini sobre o footer, tem páginas nas quais ele ainda está fixo no bottom da tela visível o tempo todo.... p.ex.: http://0.0.0.0:8000/especialistas/ ....

**Comment by diraol** [comment]
Inclusive, nessa página mesmo o header está sobrepondo parte do conteúdo.....

**Comment by vanessametonini** [comment]
Sim, percebi também, vou dar uma olhada nisso :)

**Comment by vanessametonini** [comment]
@diraol acabei de commitar na branch front as correções!
