### ISSUE TITLE
 Adequar toda a plataforma Carcerópolis para nova identidade visual da Conectas

### ISSUE THREAD

**Issue by hsvab** [ask-ar/carceropolis#72]

**Comment by vanessametonini** [comment]
@diraol acho que isso que me deixou confusa em relação as cores do infografico

**Comment by vanessametonini** [comment]
https://github.com/ask-ar/carceropolis/pull/83

**Comment by vanessametonini** [comment]
@hsvab @diraol esse ficou concluído?
