### ISSUE TITLE
Permitir adicionar mais de uma variável ao eixo Y do painel de dados

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#78]

**Comment by andresmrm** [comment]
Possíveis pendências:
- No gráfico de círculos (scatter) uma bolinha pode ocultar outra (o mesmo pode acontecer com o de linhas).
- O tooltip mostra todos os dados da coluna, não apenas o ponto com mouse.

**Comment by diraol** [comment]
@andresmrm ficou muito legal!!!!!

De fato precisamos fazer o ajuste com relação ao tooltip.

Sobre as bolinhas, eu diria que "é a vida" se houver sobreposição, ai não tem muito o que fazer.

**Comment by andresmrm** [comment]
Melhorei os tooltips.
Sobre as bolinhas, talvez dê para deixá-las semi-transparentes, dai mais ou menos daria para ver.
