### ISSUE TITLE
Geolocalizar Unidades Prisionais

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#80]

**Comment by andresmrm** [comment]
Por enquanto mapeei os dados usando o nome da cidade como informação mais precisa (não o endereço), assim diminui a taxa de não encontrados. Usei o OSM, mapeou uns 1400 de 1500.

Estou usando uma lib chamada `Geocoder`. Ela suporta várias APIs:
https://github.com/DenisCarriere/geocoder#providers

Para usar o Google precisa de uma API KEY, a chave que vem com a lib já estorou o número de acessos.

**Comment by diraol** [comment]
@andresmrm algumas unidades tiveram problema na localização? É que quando coloquei o mapa para funcionar apareceram algumas localizadas estranhamente....

**Comment by andresmrm** [comment]
Teve uma cidade só que ele não encontrou, então usei Google Maps.
Lembrando que eu geolocalizei pelas cidades, então o ponto não vai cair exatamente em cima da unidade prisional. Ou o ponto estava muito longe do esperado?

**Comment by andresmrm** [comment]
Modifiquei o comando geolocalizador para tentar achar latitudes e longitudes na seguinte ordem:

1. endereço completo via OSM
2. endereço completo via GMaps
3. cidade via OSM
4. cidade via GMaps

(quando não acha em uma passa para a próxima)

Aparentemente nenhuma unidade ficou sem geolocalização.

Atualizei o `initialdata.json.bz2` de acordo.

https://github.com/ask-ar/carceropolis/commit/2373197cdd383d0563d693e8acc08bfbf72c9faa
