### ISSUE TITLE
Carregar dados das Unidades Prisionais no BD

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#84]

**Comment by andresmrm** [comment]
Percebi que para carregar os dados das Unidades, precisava das PKs das Cidades. Depois de tentar consultá-las do BD do Django a partir do script sem muito sucesso, decidi gerar as fixtures das Cidades e das Unidades ao mesmo tempo (assim tinha as PKs das Cidades no mesmo script para consultar).

Sendo assim, criei uma pasta "fixture_generator", movi o `brazil-cities-states.json` e o `generate_fixture.py2` para lá. Esse segundo eu renomeei para `cidades_e_unidades.py` e incrementei para carregar os dados das Unidades também.

Na importação tive os seguintes problemas com a planilha:

- A cidade Mo**g**i Mirim estava escrita como Mo**j**i Mirim. Corrigi na planilha.
- "Penitenciária II de Pres. Venceslau" estava sem município. Dei uma pesquisada e pelo visto fica em Presidente Venceslau mesmo. Corrigi na planilha.

Coloco a planilha no repositório?

**Comment by diraol** [comment]
Hum... Se não me engano tem um método na classe do modelo das Unidades
Prisionais para importar o CSV.... =/

Em 16 de jan de 2018 11:32 PM, "Andrés Martano" <notifications@github.com>
escreveu:

**Comment by andresmrm** [comment]
Ixi... Agora já foi... =/

Quando conversamos na segunda, eu tinha entendido que você já havia feito a
importação desses dados antes, e ia me mandar o código para fazer isso.
Mas quando ontem você só comentou sobre os comandos:

	manage.py dumpdata --natural-foreign -e sessions -e admin -e contenttypes -e auth.Permission > initialdata.json

e

	./manage.py loaddata initialdata.json

E disse para eu subir as unidades prisionais, como esses comandos não resolvem esse problema, entendi que era para eu completar com o que faltasse. E nem passou pela minha cabeça olhar na classe do model para ver se já havia algo para isso lá. Malz...

**Comment by andresmrm** [comment]
O fato de eu ter importado usando um novo código talvez possa gerar problemas de diferentes formas de tratamento dos dados, caso mais para frente seja usado o método que está na classe do model. Mas, para não perder mais tempo com isso agora, vou deixar como está.

Gerei a fixture com todos os dados novos (agora geolocalizados no nível de cidade), e commitei. Vou fechar essa issue por enquanto.
