### ISSUE TITLE
Decidir qual servidor de tiles usar para o mapa

### ISSUE THREAD

**Issue by andresmrm** [ask-ar/carceropolis#85]
Tinha dito que precisávamos de um servidor de tiles pago para usar em produção. Mas pelo que eu vi hoje já existem gratuítos:
https://wiki.openstreetmap.org/wiki/TMS
https://wiki.openstreetmap.org/wiki/Tile_servers

Estou usando um do CartoDB (que é gratuíto e permite até 75K views/mês), mas existem outros para escolher. Fica como uma escolha de design do site. Só há que ficar atento para os termos/política de uso.

**Comment by diraol** [comment]
Então, a conectas liberou usarmos o MapBox.
Mas, dado que o CartoDB suporta até 75k views, pode ser uma alternativa boa hein!

Acho que vale só avaliarmos quais são os styles que um e outro oferecem e, em especial, se oferecem vector tyles (são bem mais rápidos que raster).
Ah, e qual o eventual custo adicional no cartoDB para o caso de passarmos de 75k views (improvável)

**Comment by diraol** [comment]
@andresmrm você está usando uma "Conta sua" ou criou uma conta para isso?

**Comment by andresmrm** [comment]
Não tenho certeza, mas acho que está usando a chave do tutorial do Leaflet.
Ou seja, precisa criar uma conta e trocar sim.

**Comment by andresmrm** [comment]
Estou vendo aqui, estamos usando servidor do CartoDB:
https://github.com/ask-ar/carceropolis/blob/bokeh_dashboard_map_charts/carceropolis/carceropolis/static/js/map.js#L83
Que aparentemente não tem restrição:
https://wiki.openstreetmap.org/wiki/Tile_servers

**Comment by hsvab** [comment]
@diraol podemos fechar essa issue?
