### ISSUE TITLE
Dados Gerais - Gráfico 2 - Evolução da População Prisional Brasileira

### ISSUE THREAD

**Issue by hsvab** [ask-ar/carceropolis#87]
- Título do gráfico: Evolução da População Prisional Brasileira
- Gráfico: dados no csv; tipo de gráfico: linha; na ausência de dados interromper
- Fonte: Ministério da Justiça; Levantamento de Informações Penitenciárias - Ministério da Justiça (2005 – 2016).
- Notas: [1] Dados referentes ao mês de dezembro de cada ano, exceto para o ano de 2002, em
que o dado refere-se a junho.
[2] Os dados consideram as pessoas custodiadas nas unidades do sistema prisional e nos
espaços de custódia geridos pelos órgãos da segurança pública.
[dados_gerais_02.zip](https://github.com/ask-ar/carceropolis/files/1671832/dados_gerais_02.zip)

**Comment by andresmrm** [comment]
Coloquei umas bolinhas em cada ponto, se não os pontos que estavam isolados (sem registros no ano anterior ou posterior) não geravam segmentos.

![](https://screenshotscdn.firefoxusercontent.com/images/ff1cef31-52b6-4905-a1cb-09e1bc68d82c.png)

**Comment by hsvab** [comment]
Os rótulos de dados apareceme de alguma forma?

**Comment by andresmrm** [comment]
Quando passa o mouse por cima aparece um tooltip dizendo a População e Ano do ponto. É isso que você perguntou?

**Comment by andresmrm** [comment]
Já migrei (plotly->bokeh) os outros 3 gráficos que estavam na página de dados gerais.
Vi no Produto1 que ela não cita o gráfico que compara os países. É para manter mesmo assim, né?

**Comment by diraol** [comment]
Apenas para fins de registro, sim, vamos mantë-lo! =)
