### ISSUE TITLE
[Infográfico][DadosGerais]

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#90]
No infográfico principal, alterar:

> "É como se todos os moradores de Aracaju estivessem atrás das grades."

para 

> "É como se todos os moradores de Amapá estivessem atrás das grades."

e alterar o gráfico de fundo para o estado do Amapá

- [x] Texto
- [x] Mapa de fundo
- [x] Alinhas o texto sobre o mapa na parte superior direita;
- [x] Deixar o limite do estado mais evidente (talvez dar um pouco mais de transparência para os outros estados?)

**Comment by vanessametonini** [comment]
@diraol comitei na branch `bokeh_dashboard_map_charts` pq é a que está com o CSS mais atualizado, se não ia dar muita dor de cabeça pra merge.

**Comment by vanessametonini** [comment]
![screen shot 2018-02-21 at 09 54 24](https://user-images.githubusercontent.com/3089882/36481281-201f953c-16ee-11e8-9a44-5f0cb46c3baf.png)

**Comment by diraol** [comment]
Mais dois itens lá na descrição da issue.
