### ISSUE TITLE
[infográfico][infraestrutura] Ajustes

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#98]
* [x] **Animação**: Neste caso acho que a animação não pode ser "automática" (timer). Se alguém não conseguir ler um dos textos vai acabar perdendo informação ou tendo que recarregar a página. Assim, acho que vale mais à pena colocar uma seta acima e uma seta abaixo do box com os bonequinhos para que a pessoa clique e faça o "slide passar". Colocar as setas ao lado do quadro com os bonequinhos.
* [x] **Estilo**: A foto também pode ser diminuída um pouco (cortar na parte de cima) para que o texto que vem abaixo (déficit de vagas) possa caber junto na mesma tela.
* [x] **[Bonus point]**: Se rolar, manter as "celas anteriores" para dar a impressão de que novos presos chegaram ao invés de substituir completamente uma pela outra.
* [x] A "setinha/flechinha" ficou meio escondida demais. Acho que podemos tentar colocá-la à direita da animação e deixá-la um pouco maior/mais grossa para chamar um pouco mais de atenção.

**Comment by vanessametonini** [comment]
O que acham dos presos que vão somando terem cores diferentes e ficarem um meio por cima dos outros?... pq encaixar 48 pessoas naquele quadradinho é realmente difícil :'(

**Comment by diraol** [comment]
Van, não vejo problema de haver sobreposição entre os elementos. Isso inclusive posso ajudar na sensação de "Superlotação".
Mas cores diferentes acho que pode ficar muito carnavalesco..... =/

**Comment by diraol** [comment]
Novo item

**Comment by diraol** [comment]
Ficou ótimo Van! =)
