### ISSUE TITLE
[Infográfico][Trabalho e Educação] Ajustes

### ISSUE THREAD

**Issue by diraol** [ask-ar/carceropolis#99]
* [x] Melhorar a qualidada da imagem que está no fundo do box;
* [x] Trocar o texto que vai sobre a imagem de ```+ de 40 % das unidades prisionais no brasil não contam com salas de aula``` para ```50% da população prisional não tem ensino fundamental completo em comparação com 25% da população em geral.``` (fazer a devida adaptação visual);
* [x] Adaptar o texto da iconografia abaixo da imagem de: `A capacidade atual precisaria ser` para `A capacidade atual de salas de aula`;
* [x] Reduzir o espaçamento vertical entre os dois itens na parte de `capacidade atual` e `multiplicada por 16`;
* [x] Substituir a última parte (`20%...`) pela frase `3 em 4 cada pessoas presas que trabalham recebem menos de 3/4 de salário mínimo, em desacordo com a Lei de Execução Penal.`, utilizando iconografia similar à última do card "Situação Jurídica".
* [x] Deslocar para a direita o texto “em comparação com 25% da população em geral”. A ideia é criar visualmente uma oposição entra as duas informações (da população prisional e da população em geral).
* [x] Inserir texto “precisa ser” (com mesmo peso de “salas de aula”) em: “_A capacidade atual de salas de aula **precisa ser** multiplicada por 16 para atender à população prisional._”
* [x] Deixar em 2 linhas (e não em 3 linhas) o texto “3 em cada 4 pessoas presas que trabalham recebem menos de ¾ de salário mínimo, em desacordo com a Lei de Execução Penal.”
* [x] Deixar o texto inteiro com fonte branca.

**Comment by diraol** [comment]
Updated

**Comment by vanessametonini** [comment]
Assim? (1)
![1](https://user-images.githubusercontent.com/3089882/39400312-9682d000-4b04-11e8-9012-330c2ed6dc47.png)

ou assim? (2)
![2](https://user-images.githubusercontent.com/3089882/39400314-9b1c7242-4b04-11e8-8f59-c0c08cfa7371.png)

**Comment by vanessametonini** [comment]
ou assim?  (3)
![3](https://user-images.githubusercontent.com/3089882/39400325-bd302f2c-4b04-11e8-89f6-da9ec2eb790f.png)

**Comment by hsvab** [comment]
A última opção "precisa ser multiplicada por 16" na mesma linha.
